sourcemeta/core

README.markdown
=> Clarify that `.clear()` works on arrays

README.markdown, include/jsontoolkit/json/rapidjson/read.h, test/json_read_test.cc
=> Implement `make_object` and `make_array` constructors

README.markdown
=> Document how to convert existing instances to arrays/objects

README.markdown
=> Note functions that are useful for programatically creating containers

test/json_write_test.cc
=> Test programatically creating objects and arrays

.github/workflows/ci.yml, CMakeLists.txt, Makefile, README.markdown
=> Do not build `contrib/` programs by default

README.markdown
=> Add FetchContent usage instructions

.github/workflows/ci.yml, CMakeLists.txt, Makefile, README.markdown
=> Do not build tests by default

CMakeLists.txt, README.markdown
=> Reduce required C++ version to 17

README.markdown
=> Improve contribution instructions

CMakeLists.txt, include/jsontoolkit/json/rapidjson/common.h, test/jsontestsuite.cc
=> Minor fixes to support Windows

CMakeLists.txt, README.markdown, cmake/rapidjson.cmake
=> Support a custom backend path

test/contrib/CMakeLists.txt
=> Do not run stdin contrib tests on Windows

test/contrib/CMakeLists.txt
=> Extract contrib test scripts into variables

.github/workflows/ci.yml, Makefile, README.markdown
=> Specify --build-config when running ctest

test/contrib/CMakeLists.txt
=> Fix Windows stdin checks

cmake/rapidjson.cmake
=> Support finding rapidjson from vcpkg

CMakeLists.txt, README.markdown, include/jsontoolkit/jsonschema.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_metaschema_test.cc
=> Implement a metaschema() function

CMakeLists.txt, README.markdown, cmake/clang-format.cmake, include/jsontoolkit/jsonschema.h, src/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_is_schema_test.cc
=> Refactor metaschema() to solve one-definition-rule problem

.github/workflows/ci.yml, Makefile, README.markdown
=> Specify `--config` when building using CMake

test/json/CMakeLists.txt, test/json/json_iterators_test.cc, test/json/json_parse_error_test.cc, test/json/json_read_test.cc, test/json/json_stringify_test.cc, test/json/json_write_test.cc
=> Simplify JSON unit tests

README.markdown, include/jsontoolkit/jsonschema.h, src/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_id_test.cc
=> Implement a JSON Schema `id()` function

CMakeLists.txt, README.markdown, include/jsontoolkit/json/rapidjson/iterators.h, include/jsontoolkit/jsonschema.h, include/jsontoolkit/jsonschema/resolver.h, src/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_vocabulary_test.cc
=> Implement a function to return schema vocabularies

.ackrc
=> Ignore `vendor/` in `.ackrc`

README.markdown, include/jsontoolkit/json/rapidjson/read.h, test/json/json_read_test.cc
=> Implement a function to deep-copy a JSON document or value

CMakeLists.txt, README.markdown, contrib/jsonschema-walker/CMakeLists.txt, contrib/jsonschema-walker/walker.cc, include/jsontoolkit/jsonschema.h, include/jsontoolkit/jsonschema/walker.h, src/jsonschema.cc, src/jsonschema/walker.cc, test/contrib/CMakeLists.txt, test/contrib/example-2020-12-subschemas.txt, test/contrib/example-2020-12.json, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_walker_test.cc
Fixes: https://github.com/sourcemeta/jsontoolkit/issues/48
=> Implement support for iterating over subschemas

Makefile
=> Increase granularity of GNU Make targets

README.markdown, include/jsontoolkit/jsonschema.h, src/jsonschema.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Let vocabularies() take an optional default metaschema URI

Makefile, www/CNAME, www/template.html
=> Change domain to jsontoolkit.org

CMakeLists.txt
=> Enable pthreads on Linux

.github/workflows/ci.yml
=> Test building on GNU/Linux using GCC

CMakeLists.txt, contrib/jsonschema-keywords/CMakeLists.txt, contrib/jsonschema-keywords/main.cc, test/contrib/CMakeLists.txt, test/contrib/is_same.sh, test/contrib/is_same_stdin.sh, test/contrib/schemas/arrays.schema.json, test/contrib/schemas/geographical-location.schema.json, test/contrib/schemas/keyword-count.txt, test/contrib/schemas/person.schema.json
=> Add a contrib tool to analyze JSON Schema keywords

README.markdown, include/jsontoolkit/jsonschema.h, src/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_dialect_test.cc
=> Implement a function to determine the schema's dialect URI

src/jsonschema.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Assume core vocabularies if $vocabulary is unset

include/jsontoolkit/jsonschema.h, test/jsonschema/jsonschema_walker_test.cc
=> Fix `flat_subschema_iterator()` on schema without a metaschema

README.markdown, include/jsontoolkit/jsonschema/default_walker.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_walker_test.cc
=> Define a schema walker that never walks

README.markdown, include/jsontoolkit/json/write.h, test/json/json_write_test.cc
=> Implement `erase_many()`

README.markdown
=> Document GCC support

README.markdown, test/json/json_write_test.cc
=> Minor misc fixes for `erase_many()`

README.markdown, include/jsontoolkit/json/read.h, test/json/json_read_test.cc
=> Define `defines_any()`

README.markdown
=> Fix `push_back()` docs example

README.markdown, include/jsontoolkit/json/read.h, test/json/json_read_test.cc
=> Implement `is_number()`

include/jsontoolkit/json/rapidjson/read.h, test/json/json_read_test.cc
=> Support using `from()` with `std::size_t`

README.markdown
=> Document the `contains()` array function

README.markdown, include/jsontoolkit/json/rapidjson/read.h, test/json/json_iterators_test.cc, test/json/json_read_test.cc
=> Implement a "compare" function for standard algorithms

README.markdown, include/jsontoolkit/json/rapidjson/write.h, include/jsontoolkit/json/write.h, test/json/json_iterators_test.cc
=> Generalize iterator-based `erase_many` to work on arrays

README.markdown, include/jsontoolkit/json/rapidjson/write.h, include/jsontoolkit/json/write.h, test/json/json_write_test.cc
=> Implement a `clear_except()` function for objects

Makefile
=> Make Makefile NMAKE compliant

test/json/jsontestsuite.cc
=> Disable some JSONTestSuite tests for MSVC

include/jsontoolkit/json/rapidjson/read.h
=> Fix cast to make MSVC happy

.github/workflows/ci.yml, CMakeLists.txt, README.markdown, cmake/vcpkg.cmake
=> Add basic Windows support

Makefile
=> Create a new "test" target in the Makefile

CMakeLists.txt
=> Disable min/max macros on MSVC

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Throw if the core vocabulary is missing or set to optional

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Better handle vocabularies for boolean schemas

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Check current dialect when fetching vocabularies

src/jsonschema/jsonschema.cc
=> Make `vocabularies()` dialect-aware

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Add 2019-09 support in `vocabularies()`

src/jsonschema/jsonschema.cc
=> Note intention to support older JSON Schema dialects in `.vocabularies()`

src/json/include/jsontoolkit/json/rapidjson/read.h
=> Ensure doubles are never NaN or infinity

LICENSE
=> Re-license the project as AGPL

README.markdown, src/json/include/jsontoolkit/json/read.h, test/json/json_read_test.cc
=> Implement a `to_vector()` utility function

README.markdown, src/json/include/jsontoolkit/json/read.h, test/json/json_read_test.cc
=> Implement an `is_positive()` utility function

src/json/include/jsontoolkit/json/iterators.h, src/json/include/jsontoolkit/json/rapidjson/iterators.h
=> Be explicit about JSON iterator begin/end types

src/json/include/jsontoolkit/json/rapidjson/iterators.h
=> Add iterator traits to JSON iterators

src/jsonschema/include/jsontoolkit/jsonschema.h
=> Declare `iterator` and `const_iterator` for `SchemaWalker`

.github/workflows/ci.yml, Makefile
=> Run CMake parallel builds by default

.github/workflows/ci.yml, Makefile
=> Run tests in parallel

src/json/include/jsontoolkit/json/rapidjson/write.h, test/json/json_write_test.cc
=> Properly allocate keys on object assignment

README.markdown, src/json/include/jsontoolkit/json/rapidjson/common.h, src/json/include/jsontoolkit/json/rapidjson/read.h, test/json/json_read_test.cc
=> Implement a hash function for JSON documents

README.markdown
=> Mention FreeBSD support

CMakeLists.txt
=> Install README on the package docs directory

README.markdown, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Define library aliases

.github/workflows/ci.yml, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Always perform component-based installation

contrib/jsonschema-keywords/CMakeLists.txt, contrib/jsonschema-walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt
=> Allow installing contrib programs

contrib/jsonschema-keywords/CMakeLists.txt, contrib/jsonschema-walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt, src/jsonschema/CMakeLists.txt, test/json/CMakeLists.txt, test/jsonschema/CMakeLists.txt
=> Use :: namespaced target aliases

src/json/CMakeLists.txt
=> Correctly define header sources in JSON interface library

src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Set correct output/export names for libraries

CMakeLists.txt
=> Only install README on top-level builds

cmake/compiler.cmake, contrib/jsonschema-keywords/CMakeLists.txt, contrib/jsonschema-walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt, test/json/CMakeLists.txt, test/jsonschema/CMakeLists.txt
=> Remove warnings macro in favor of global options

src/json/include/jsontoolkit/json/rapidjson/common.h
=> Ignore -Wdocumentation for RapidJSON

Makefile
=> Exercise installation on local builds

src/json/CMakeLists.txt
=> Declare top-level JSON header as part of the JSON library

cmake/rapidjson.cmake, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Install library CMake exports

cmake/rapidjson.cmake
=> Turn rapidjson wrapper into an imported target

.cirrus.yml, .github/workflows/ci.yml, CMakeLists.txt, README.markdown, cmake/JSONToolkitConfig.cmake.in, cmake/rapidjson.cmake, test/packaging/CMakeLists.txt, test/packaging/find_package/CMakeLists.txt, test/packaging/find_package/hello.cc
=> Make the project consumable by CMake `find_package()`

.github/workflows/ci.yml, cmake/vcpkg.cmake, vcpkg.json
=> Better integrate with VCPKG on Windows

.github/workflows/ci.yml, Brewfile
=> Add a Brewfile for macOS dependencies

src/jsonschema/CMakeLists.txt
=> Remove artificial JSON Schema `resolver.h` install

README.markdown, src/json/CMakeLists.txt, src/json/include/jsontoolkit/json/error.h, src/json/include/jsontoolkit/json/rapidjson/read.h, test/json/CMakeLists.txt, test/json/json_error_test.cc, test/json/json_parse_error_test.cc, test/json/jsontestsuite.cc
=> Implement a basic `ParseError` exception subclass

src/jsonschema/CMakeLists.txt, src/jsonschema/include/jsontoolkit/jsonschema.h, src/jsonschema/include/jsontoolkit/jsonschema/error.h, src/jsonschema/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_error_test.cc, test/jsonschema/jsonschema_metaschema_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Introduce a general purpose `SchemaError` exception subclass

src/json/include/jsontoolkit/json/error.h, src/jsonschema/include/jsontoolkit/jsonschema/error.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_draft_test.cc, test/jsonschema/jsonschema_error_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Implement a `ResolutionError` exception subclass

src/json/include/jsontoolkit/json/rapidjson/read.h, test/json/json_read_test.cc
=> Support calling `from()` with a `std::string_view`

DEPENDENCIES, cmake/compiler.cmake, vendor/noa/cmake/noa.cmake, vendor/noa/cmake/noa/defaults.cmake, vendor/noa/cmake/noa/variables.cmake
=> Use Noa's compiler variables

CMakeLists.txt, DEPENDENCIES, cmake/compiler.cmake, vendor/noa/cmake/noa.cmake, vendor/noa/cmake/noa/defaults.cmake, vendor/noa/cmake/noa/variables.cmake
=> Simplify ISO C++ settings with Noa

DEPENDENCIES, vendor/noa/cmake/noa/defaults.cmake
=> Upgrade Noa to handle RPATHs

DEPENDENCIES, contrib/jsonschema-keywords/main.cc, contrib/jsonschema-walker/walker.cc, contrib/minify/minify.cc, contrib/prettify/prettify.cc, src/json/include/sourcemeta/jsontoolkit/json/error.h, src/json/include/sourcemeta/jsontoolkit/json/rapidjson/iterators.h, src/json/include/sourcemeta/jsontoolkit/json/rapidjson/read.h, src/json/include/sourcemeta/jsontoolkit/json/rapidjson/write.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/error.h, src/jsonschema/jsonschema.cc, vendor/noa/cmake/noa/targets/clang-tidy.config
=> Address ClangTidy comments

CHANGELOG.markdown
=> Add a CHANGELOG template

.github/workflows/ci.yml, CMakeLists.txt, Makefile, src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/default_resolver.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/default_walker.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/error.h
=> Support shared libraries

CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Refactor JSON Schema library declaration

.github/workflows/ci.yml, CMakeLists.txt, Makefile, contrib/jsonschema_keywords/CMakeLists.txt, contrib/jsonschema_walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Rename main component to `sourcemeta_jsontoolkit`

Makefile, README.markdown, contrib/jsonschema_keywords/CMakeLists.txt, contrib/jsonschema_walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt
=> Separate `contrib` tools into their own component

.github/workflows/ci.yml, CMakeLists.txt, Makefile, README.markdown, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Create a separate `sourcemeta_jsontoolkit_dev` component

CMakeLists.txt
=> Set HOMEPAGE_URL in the CMake project declaration

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h
=> Improve conditional with ClangTidy suggestions

src/json/include/sourcemeta/jsontoolkit/json/rapidjson/iterators.h
=> Quiet ref member ClangTidy warnings

.github/workflows/ci.yml, Makefile, README.markdown
=> Be explicit about CMake variable types

DEPENDENCIES, vendor/noa/cmake/noa/defaults.cmake
=> Improve GoogleTest discovery defaults

test/packaging/CMakeLists.txt
=> Use typed CMake variables in packaging tests

DEPENDENCIES, contrib/jsonschema_keywords/CMakeLists.txt, contrib/jsonschema_walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt, src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt, test/json/CMakeLists.txt, test/jsonschema/CMakeLists.txt, vendor/noa/cmake/noa/defaults.cmake, vendor/noa/cmake/noa/targets/clang-format.cmake, vendor/noa/cmake/noa/targets/clang-tidy.cmake, www/CMakeLists.txt
=> Configure IDE folders in CMake

CMakeLists.txt, README.markdown, cmake/rapidjson.cmake
=> Remove support for specifying a backend path

src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/default_resolver.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/default_walker.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/error.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema/jsonschema.h
=> Rename export header

test/json/json_read_test.cc
=> Unit test `compare()` with equal strings

CMakeLists.txt, DEPENDENCIES, vendor/noa/cmake/noa/compiler/sanitizer.cmake
=> Apply sanitizers per target

src/json/parser.h, test/json/jsontestsuite.cc
=> Enable remaining JSONTestSuite cases

src/json/include/sourcemeta/jsontoolkit/json_value.h
=> Use trailing return types

src/json/grammar.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/parser.h
=> Add various grammar comments

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/json.cc, test/json/json_value_test.cc
=> Override `operator<<` for JSON

contrib/jsonschema_keywords/CMakeLists.txt, contrib/jsonschema_walker/CMakeLists.txt, contrib/minify/CMakeLists.txt, contrib/prettify/CMakeLists.txt, test/contrib/CMakeLists.txt
=> Improve contrib target names

src/json/include/sourcemeta/jsontoolkit/json_array.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/include/sourcemeta/jsontoolkit/json_value.h
=> Fix various MSVC DLL warnings

doxygen/index.markdown
=> Recommend C++20 on installation examples

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_string_test.cc
=> Support initializing from `string_view`

src/jsonpointer/jsonpointer.cc
=> Simplify JSON Pointer "get" branch

test/jsonpointer/jsonpointer_get_test.cc
=> Cover JSON Pointer RFC tests

src/jsonpointer/jsonpointer.cc
=> Improve JSON Pointer "get" inline docs

test/json/json_parser_test.cc
=> Test a JSON string with an null byte inside

test/jsonpointer/jsonpointer_get_test.cc
=> Test presence of null in an object property

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_set_test.cc
=> Implement a "set" operator for JSON Pointer

test/jsonpointer/jsonpointer_set_test.cc
=> Test JSON Pointer setting to a hyphen property

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, test/jsonpointer/jsonpointer_get_test.cc, test/jsonpointer/jsonpointer_token_test.cc
=> Support the concept of a JSON Pointer hyphen constant

src/jsonpointer/jsonpointer.cc
=> Use iterators to traverse JSON Pointers

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json.cc, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc
=> Declare JSON char and char_traits types

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_grammar.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/jsonpointer_set_test.cc
=> Support setting to the hyphen JSON Pointer token in arrays

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_grammar.h, src/jsonpointer/jsonpointer.cc, src/jsonpointer/stringify.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_stringify_test.cc
=> Add support for stringifying JSON Pointers

src/json/stringify.h, src/jsonpointer/stringify.h, test/json/json_stringify_test.cc
=> Correctly stringify control characters in JSON

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h
=> Fix JSON Pointer stringify Doxygen group

contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/walker.cc, contrib/minify/minify.cc, contrib/prettify/prettify.cc, src/json/include/sourcemeta/jsontoolkit/json.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json.cc, src/json/parser.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonschema/default_resolver.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, test/json/json_array_test.cc, test/json/json_number_test.cc, test/json/json_object_test.cc, test/json/json_parse_error_test.cc, test/json/json_parser_test.cc, test/json/json_value_test.cc, test/json/jsontestsuite.cc, test/jsonpointer/jsonpointer_get_test.cc, test/jsonpointer/jsonpointer_set_test.cc, test/jsonschema/jsonschema_draft_test.cc, test/jsonschema/jsonschema_id_test.cc, test/jsonschema/jsonschema_is_schema_test.cc, test/jsonschema/jsonschema_metaschema_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Rename `parse` to `parse_json`

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Implement `emplace_back` for pointers

src/json/include/sourcemeta/jsontoolkit/json_value.h
=> Support C++17 in the JSON component

Config.uk, Makefile.uk, doxygen/index.markdown
=> Add basic Unikraft support

src/jsonpointer/jsonpointer.cc
=> Simplify syntax for accessing JSON Pointer iterators

test/jsonpointer/jsonpointer_get_test.cc, test/jsonpointer/jsonpointer_set_test.cc
=> Test pointers that traverse objects using integer indexes

cmake/Doxygen.cmake
=> Make Doxygen optional

test/packaging/CMakeLists.txt
=> Match `CMAKE_BUILD_TYPE` on packaging tests

DEPENDENCIES, vendor/noa/cmake/noa/defaults.cmake
=> Upgrade Noa to get Windows library/runtime directory fixes

.github/workflows/ci.yml
=> Test generation of shared libraries on Windows

contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/walker.cc, contrib/minify/minify.cc, contrib/prettify/prettify.cc, src/json/include/sourcemeta/jsontoolkit/json.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json.cc, src/json/parser.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonschema/default_resolver.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, test/json/json_array_test.cc, test/json/json_number_test.cc, test/json/json_object_test.cc, test/json/json_parse_error_test.cc, test/json/json_parser_test.cc, test/json/json_value_test.cc, test/json/jsontestsuite.cc, test/jsonpointer/jsonpointer_get_test.cc, test/jsonpointer/jsonpointer_set_test.cc, test/jsonschema/jsonschema_draft_test.cc, test/jsonschema/jsonschema_id_test.cc, test/jsonschema/jsonschema_is_schema_test.cc, test/jsonschema/jsonschema_metaschema_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_walker_test.cc
This reverts commit 87a2444f7bfec026d21a2f532e9d02818216903e.
=> Rename `parse_json` to `parse`

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_string_test.cc
=> Implement a `to_stringstream()` method

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_error.h, test/json/json_parse_error_test.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_error_test.cc
=> Implement a `PointerParseError` class

src/jsonpointer/CMakeLists.txt, src/jsonpointer/grammar.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, src/jsonpointer/stringify.h
=> Make JSON Pointer grammar header private

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, src/jsonpointer/jsonpointer.cc, src/jsonpointer/parser.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_parse_error_test.cc, test/jsonpointer/jsonpointer_parse_test.cc
=> Add JSON Pointer parsing support

DEPENDENCIES, src/jsonschema/CMakeLists.txt, src/jsonschema/default_resolver.in.cc, vendor/jsonschema-draft7.mask, vendor/jsonschema-draft7/hyper-schema.json, vendor/jsonschema-draft7/schema.json
=> Add Draft7 metaschemas

src/jsonschema/default_resolver.in.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, test/jsonschema/jsonschema_default_resolver_test.cc, test/jsonschema/jsonschema_draft_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Make schema resolver take a string view as identifier

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h
=> Simplify `SchemaWalker` class

src/jsonschema/default_resolver.in.cc, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_default_resolver_test.cc, test/jsonschema/jsonschema_id_test.cc
=> Test presence of all official metaschemas in default resolver

contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/walker.cc, src/jsonschema/default_resolver.in.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, test/jsonschema/jsonschema_default_resolver_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Simplify official schema resolver

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, test/jsonschema/jsonschema_walker_test.cc
=> Use string views in `SchemaWalker`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/jsonschema.cc, src/jsonschema/walker.cc, test/jsonschema/jsonschema_base_dialect_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Rename mentions of default metaschema to default dialect

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_dialect_test.cc
=> Revise `dialect()` function to support all versions of JSON Schema

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_base_dialect_test.cc, test/jsonschema/jsonschema_error_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc
=> Rename `ResolutionError` to `SchemaResolutionError`

test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_dialect_test.cc, test/jsonschema/jsonschema_official_resolver_test.cc
=> Revisit official resolver tests

.github/workflows/ci.yml, Makefile
=> Set an explicit parallel build limit

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h
=> Inline `schema_walker_none`

src/jsonschema/default_walker.cc
=> Use C++20 map `contains` in default walker

test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_walker_none_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Separately and properly test `schema_walker_none`

test/jsonschema/jsonschema_walker_test.cc
=> Revise the default walker tests

src/jsonschema/default_walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_2019_09_test.cc
=> Support 2019-09 in the default walker

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Add Draft7 support to the default walker

src/jsonschema/default_walker.cc
=> Refactor the definition of the default walker

cmake/FindGoogleTest.cmake, test/json/CMakeLists.txt, test/jsonpointer/CMakeLists.txt, test/jsonschema/CMakeLists.txt
=> Don't run every GoogleTest case as a separate process

src/jsonschema/default_walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Add Draft4 support to the default walker

src/jsonschema/default_walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Add Draft3 support to default walker

src/jsonschema/default_walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_draft2_test.cc
=> Add Draft2 support to the default walker

src/jsonschema/default_walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_draft1_test.cc
=> Add Draft1 support to the default walker

src/jsonschema/default_walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_default_walker_draft0_test.cc
=> Add Draft0 support to the default walker

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc
=> Add hyper-schema walker support to 2019-09 and 2020-12

test/jsonschema/jsonschema_default_walker_draft0_test.cc
=> Test hyperschema support for Draft0 in default walker

test/jsonschema/jsonschema_default_walker_draft1_test.cc
=> Test hyperschema support for Draft1 in default walker

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc
=> Add hyperschema support for Draft2 in default walker

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Add hyperschema support for Draft3 and Draft4 in default walker

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Add hyperschema support to default walker for Draft6 and Draft7

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_id_test.cc
=> Properly implement the `id` based on dialects

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/include/sourcemeta/jsontoolkit/uri_error.h
=> Document the new URI module

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_fragment_test.cc, test/uri/uri_host_test.cc
=> Implement a `fragment` method on the URI class

src/uri/CMakeLists.txt, src/uri/escaping.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, test/uri/CMakeLists.txt, test/uri/uri_escape_test.cc, test/uri/uri_unescape_test.cc
=> Implement URI escaping/unescaping

src/uri/include/sourcemeta/jsontoolkit/uri.h
=> Add TODO for constructing URIs using input streams

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Implement JSON Pointer equality support

CMakeLists.txt, config.cmake.in
=> Include JSON Pointer before JSON Schema

contrib/jsonschema_keywords/CMakeLists.txt, contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/CMakeLists.txt, contrib/jsonschema_walker/walker.cc, src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_walker_none_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Report back only JSON Pointers when walking schemas

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, src/jsonschema/walker.cc, test/jsonschema/jsonschema_dialect_test.cc
=> Take a default value in the `dialect()` function

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_test.cc
=> Add basic copy/move semantics to URI

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Add a `pop_back()` method to `Pointer`

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/uri_test.cc
=> Implement a `from_fragment` URI static factory method

Makefile.uk, patches/uriparser/0001-No-UriConfig.h-on-WebAssembly-and-Unikraft.patch, vendor/uriparser/src/UriMemory.c
=> Support JSON Pointer and URI on Unikraft

doxygen/index.markdown
=> Document how to use JSON Toolkit with Unikraft

.gitignore, Makefile, unikraft/Kraftfile, unikraft/Makefile.uk
=> Setup a Unikraft project for running JSON Toolkit tests

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_walker.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_walker_test.cc, unikraft/Makefile.uk
=> Implement a subpointer walker

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc
=> Fix Draft0, Draft1, and Draft2 hyper schema walkers

src/jsonschema/reference.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_frame_test.cc, unikraft/Makefile.uk
=> Support JSON Schema framing when mixing dialects

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Revise `frame()` to ignore dynamic anchors for now

.github/workflows/ci.yml
=> Use `-latest` runners on GitHub Actions

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Report dialect URI on `frame()`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h
=> Fix documentation example for `frame()`

patches/uriparser/0002-No-BUILD_SHARED_LIBS-option.patch, vendor/uriparser/CMakeLists.txt
=> Ensure `uriparser` doesn't affect `BUILD_SHARED_LIBS`

.github/workflows/ci.yml
See: https://github.com/actions/runner-images/issues/8659
=> Attempt to workaround Clang Ubuntu issues on GitHub Actions

.github/workflows/ci.yml
Fixes: https://github.com/sourcemeta/jsontoolkit/issues/233
=> Run Unikraft build GitHub Actions

.github/workflows/ci.yml
=> Run Unikraft build using QEMU on CI

Makefile
=> Don't run `kraft fetch` on the Makefile for local development

test/packaging/find_package/CMakeLists.txt
=> Build packaging example with C++20

.github/workflows/ci.yml
=> Fix ctest comment on GitHub Actions

Brewfile
=> Add Doxygen to the Brewfile

.github/workflows/ci.yml
=> Run `apt-get update` on GitHub Actions

Config.uk, unikraft/Kraftfile
=> Extend `Config.uk` to list all requirements

.github/workflows/ci.yml
=> Run `apt-get update` on Unikraft pipelines

LICENSE-PATRON.markdown, README.markdown
=> Add a Patron license

test/json/json_parse_error_test.cc
=> Test that backspace is not whitespace according to JSON

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_host_test.cc, test/uri/uri_port_test.cc
Depends-On: https://github.com/sourcemeta/jsontoolkit/pull/352
=> Extend the URI class to get port numbers

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Accept an optional default id in `frame()`

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/json.cc, src/json/parser.h, test/json/json_parse_test.cc
=> Optionally take read/write line/column on JSON parsing

test/uri/uri_fragment_test.cc
=> Test parsing a URI that consists of an invalid fragment

.github/workflows/ci.yml
=> Run test workflow once every working day

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_host_test.cc, test/uri/uri_path_test.cc
=> Implement a method to get a URI path

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_is_urn_test.cc
=> Add a method to check whether a URI is a URN

src/uri/uri.cc, test/uri/uri_fragment_test.cc, test/uri/uri_host_test.cc, test/uri/uri_is_absolute_test.cc, test/uri/uri_path_test.cc, test/uri/uri_port_test.cc, test/uri/uri_recompose_test.cc, test/uri/uri_scheme_test.cc
=> Test current URI methods against URNs

test/uri/uri_fragment_test.cc, test/uri/uri_path_test.cc, test/uri/uri_scheme_test.cc
=> Test URNs that contain fragments

test/uri/uri_fragment_test.cc, test/uri/uri_recompose_test.cc
=> Add tests exercising URIs with empty fragments

test/uri/uri_recompose_test.cc
=> Add test exercising URI recomposing with trailing slash path

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h
=> Fix `frame()` Doxygen example

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_empty_pointer_test.cc
=> Add a constant that represents the empty pointer

src/jsonschema/reference.cc
=> Extend `.frame()` to work on multiple URI bases

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Handle framing with explicit different IDs

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_query_test.cc
=> Implement a basic method to get the query part of a URI

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_canonicalize_test.cc
=> Implement a simple URI canonicalize method

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_canonicalize_test.cc, test/uri/uri_is_tag_test.cc, test/uri/uri_is_urn_test.cc, test/uri/uri_path_test.cc
=> Implement support for tag URIs

src/jsonschema/reference.cc
=> Canonicalize when storing URIs to reference frames

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Add basic URI iterator support to `ReferenceFrame`

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_walker.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_walker_test.cc, unikraft/Makefile.uk
=> Implement a general-purpose JSON walker with JSON Pointer

unikraft/Makefile.uk
=> Add missing URI tests to Unikraft test runner app

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_resolve_from_test.cc, unikraft/Makefile.uk
=> Implement JSON Pointer relative resolution

src/jsonschema/reference.cc
=> Refactor `frame()` find bases internal function

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_to_string_test.cc, unikraft/Makefile.uk
=> Implement a convenient function to convert a Pointer to a string

test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Introduce an `EXPECT_FRAME` test macro

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Extend `frame()` to consider every JSON Pointer to the schema

DEPENDENCIES, vendor/referencing-suite/tests/json-schema-draft-2020-12/multiple-lookup-external-absolute-uri-with-different-id-anchor.json
=> Upgrade the JSON Schema Referencing Suite to latest

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Add a base to every `ReferenceFrame` entry

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, src/jsonpointer/stringify.h, src/jsonschema/reference.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_stringify_test.cc, test/jsonpointer/jsonpointer_to_uri_test.cc, unikraft/Makefile.uk
=> Implement a function to convert a JSON Pointer to a URI fragment

test/uri/uri_canonicalize_test.cc
=> Add URI canonicalize examples around URI escaping

DEPENDENCIES, test/jsonschema/referencingsuite.cc, vendor/referencing-suite/tests/json-schema-draft-03/keywords-additionalItems-boolean.json, vendor/referencing-suite/tests/json-schema-draft-03/keywords-additionalProperties-boolean.json, vendor/referencing-suite/tests/json-schema-draft-03/pointer-crossing-id-in-dependencies-object.json, vendor/referencing-suite/tests/json-schema-draft-03/pointer-crossing-id-in-items-array.json, vendor/referencing-suite/tests/json-schema-draft-03/pointer-crossing-id-in-items-object.json
=> Enable every test from the JSON Schema Referencing Suite

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_concat_test.cc, test/jsonpointer/jsonpointer_resolve_from_test.cc, unikraft/Makefile.uk
=> Add a method to concatenate two JSON Pointers

Makefile.uk, src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, src/jsonschema/transform_bundle.cc, src/jsonschema/transform_rule.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_transform_bundle_test.cc, test/jsonschema/jsonschema_transform_rule_test.cc, test/jsonschema/jsonschema_transform_rules.h, unikraft/Makefile.uk
=> Implement schema transformation functionality

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, src/jsonschema/transform_bundle.cc, src/jsonschema/transform_rule.cc, test/jsonschema/jsonschema_transform_rules.h
=> Make schema transformation rules report the values they modified

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h
=> Fix rule/bundle examples

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, src/jsonschema/transform_bundle.cc, src/jsonschema/transform_rule.cc, test/jsonschema/jsonschema_transform_rules.h
=> Revert schema transform rules returning set of pointers

Makefile.uk, src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transform_bundle.cc, src/jsonschema/transform_rule.cc, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transform_rules.h
=> Introduce a schema transformer proxy for transform rules

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_starts_with_test.cc, unikraft/Makefile.uk
=> Add method to check whether a Pointer starts with another Pointer

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_rebase_test.cc, unikraft/Makefile.uk
=> Implement JSON Pointer rebasing

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/jsonpointer_parse_error_test.cc, test/jsonpointer/jsonpointer_parse_test.cc
=> Let JSON Pointer instances be constructed from standard C++ strings

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Support framing references in anonymous schemas

src/jsonschema/reference.cc
=> Add TODO about anchors and anonymous frames

CMakeLists.txt, contrib/jsonschema_frame/CMakeLists.txt, contrib/jsonschema_frame/main.cc
=> Implement an example "frame" JSON Schema CLI tool

contrib/jsonschema_frame/main.cc, src/jsonschema/reference.cc
=> Cleanup Frame CLI output

CMakeLists.txt, DEPENDENCIES, doxygen/index.markdown, src/json/CMakeLists.txt, src/jsonl/CMakeLists.txt, src/jsonpointer/CMakeLists.txt, src/jsonschema/CMakeLists.txt, src/uri/CMakeLists.txt, vendor/noa/cmake/noa/library.cmake
=> Add CMake option to control component installation

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Extend framing to support pointers without a base

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Support framing pointers to `$anchor` in anonymous schemas

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Frame static anchors on anonymous schemas

test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Revise `.frame()` reference map basic tests

src/jsonschema/reference.cc
=> Remove incorrect TODOs

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend framing to resolve static references

contrib/jsonschema_frame/main.cc
=> Print references in frame CLI tool

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h
=> Document frame references

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Register top-level static anchors without identifiers

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/referencingsuite.cc
=> Extend framing to record dynamic anchors

src/jsonschema/reference.cc
=> Dereference after framing

Makefile.uk, src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference_frame.h, src/jsonschema/reference.cc, src/jsonschema/reference_frame.cc
=> Extract `ReferenceFrame` into a separate unit

src/jsonschema/reference.cc
=> Remove invalid TODO in `frame()`

CMakeLists.txt
=> Explicitly include `CompilerOptions`

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Add a `ReferenceType` qualifier to `ReferenceMap`

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_recompose_test.cc, test/uri/uri_recompose_without_fragment_test.cc, unikraft/Makefile.uk
=> Implement a method to recompose a URI without its fragment

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/uri_recompose_without_fragment_test.cc
=> Make `recompose_without_fragment()` return an optional value

src/uri/include/sourcemeta/jsontoolkit/uri.h
=> Add TODOs to URI about the benefits of supporting mutations

src/jsonschema/reference.cc
=> Add TODO for checking that static references exists in frames

test/jsonschema/jsonschema_test_utils.h
=> Simplify `TO_POINTER` macro in JSON Schema test utils

.github/workflows/ci.yml
=> Revise GitHub Actions Linux Clang CI workaround

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Check for 2020-12 Core vocabulary before framing `$dynamicRef`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference_frame.h, src/jsonschema/reference.cc, src/jsonschema/reference_frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Store the reference type in `ReferenceFrame`

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Do not frame relative anchor URIs for schemas with identifiers

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h
=> Update `frame()` description docs

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference_frame.h, src/jsonschema/reference.cc, src/jsonschema/reference_frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/referencingsuite.cc
=> Set `ReferenceType` as part of the `ReferenceFrame` key

src/jsonschema/anchor.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, test/jsonschema/jsonschema_anchor_2020_12_test.cc
=> Correctly detect anchors that are both static and dynamic

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Frame `$dynamicAnchor` for 2020-12

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, src/jsonschema/reference.cc, test/jsonschema/jsonschema_id_2019_09_test.cc, test/jsonschema/jsonschema_id_2020_12_test.cc, test/jsonschema/jsonschema_id_draft0_test.cc, test/jsonschema/jsonschema_id_draft1_test.cc, test/jsonschema/jsonschema_id_draft2_test.cc, test/jsonschema/jsonschema_id_draft3_test.cc, test/jsonschema/jsonschema_id_draft4_test.cc, test/jsonschema/jsonschema_id_draft6_test.cc, test/jsonschema/jsonschema_id_draft7_test.cc
=> Implement a convenience base dialect shortcut for `id()`

src/jsonschema/reference.cc
=> Add comment about extending `SchemaIterator` to return more information

src/jsonschema/reference.cc
=> Add a helper for checking if `$ref` overrides adjacent keywords

src/jsonschema/jsonschema.cc
=> Optimize `base_dialect()` to require less JSON parsing

src/jsonschema/jsonschema.cc
=> Optimize `vocabularies()` for 2020-12 and 2019-09

src/uri/uri.cc
=> Extract URI parser into a separate function

src/jsonschema/reference_frame.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/jsonschema/referencingsuite.cc, test/uri/uri_canonicalize_test.cc
=> Perform URI canonicalization in-place

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_test_utils.h
=> Simplify the `ReferenceMap` helper type

src/jsonschema/reference.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/jsonschema/referencingsuite.cc, test/uri/uri_resolve_from_test.cc
=> Turn `URI::resolve_from` into a method that mutates the instance

src/jsonschema/reference.cc
=> Perform a single pass over subschemas in `frame()`

test/jsonschema/jsonschema_frame_test.cc
=> Test framing remote references

contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/reference.cc, src/jsonschema/transform_bundle.cc, src/jsonschema/walker.cc, test/jsonschema/jsonschema_walker_none_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Extend `SchemaIterator` to pass metadata about each schema

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_object_test.cc
=> Implement an `assign_if_missing` JSON helper method

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_transformer_test.cc, unikraft/Makefile.uk
=> Extend SchemaTransformer to support the JSON BinPack Mapper

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, test/jsonschema/jsonschema_transform_rules.h
=> Improve docs on how to define schema transformation methods

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
=> Generalize transformer erase to take a pointer path

src/json/include/sourcemeta/jsontoolkit/json_value.h
=> Fix JSON `erase` iterator docs

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
=> Implement `erase_keys` at `SchemaTransformer`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
=> Revise transformer `erase_keys` to take iterators

CMakeLists.txt
=> De-duplicate `noa_sanitizer` commands

CMakeLists.txt, vendorpull.mask
=> Generate CMake config even on non-top level builds

config.cmake.in, doxygen/index.markdown
=> Support component-based `find_package`

unikraft/Kraftfile
=> Simplify test Kraftfile

DEPENDENCIES, vendor/noa/cmake/noa/targets/clang-tidy.cmake
=> Upgrade Noa to the latest version

cmake/FindUriParser.cmake
=> Don't install `uriparser` headers

cmake/CompilerOptions.cmake
=> Set MSVC `/permissive-`

test/contrib/CMakeLists.txt
=> Attempt to fix Windows CI scripts

.github/workflows/ci.yml, Brewfile, contrib/jsonschema_walker/walker.cc, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/parser.h, src/json/stringify.h, src/jsonl/include/sourcemeta/jsontoolkit/jsonl_iterator.h, src/jsonl/iterator.cc, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, src/jsonpointer/parser.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/jsonschema.cc, src/jsonschema/reference.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, test/jsonschema/jsonschema_transform_rules.h
=> Reformat using ClangFormat v18

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Introduce a `SchemaWalkerResult` wrapper

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Implement a mechanism to calculate keyword priority for evaluation

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/reference.cc
=> Generalize `SchemaIteratorEntry` to hold an arbitrary JSON value

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_keyword_iterator_test.cc
=> Implement a JSON Schema keyword priority-based iterator

unikraft/Makefile.uk
=> Run JSON Schema keyword iterator tests on Unikraft

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/json.cc, test/json/CMakeLists.txt, test/json/json_type_test.cc, unikraft/Makefile.uk
=> Support printing JSON types

Makefile.uk, src/jsonschema/CMakeLists.txt, src/jsonschema/compile.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_2020_12_test.cc, unikraft/Makefile.uk
=> Prototype a JSON Schema compiler

src/jsonschema/CMakeLists.txt, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h
=> Split default schema compiler into dialects

.github/workflows/ci.yml
=> Set a shell default for every entry in the matrix

src/jsonschema/CMakeLists.txt, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h, src/jsonschema/default_compiler_draft4.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_draft4_test.cc, unikraft/Makefile.uk
=> Compile "type" for Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Implement an "and" logical operator in the schema compiler

src/jsonschema/compile.cc
=> Compute effective dialect when compiling schemas

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Offer a better recursion interface on the schema compiler

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc, unikraft/Makefile.uk
=> Compile "allOf" for Draft 4

src/jsonschema/compile.cc
=> Use frame to simplify compilation boostrapping

test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend frame tests to cover bases too

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Expose relative pointers when framing schemas

src/jsonschema/compile.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Rename `schema_location` to `evaluation_path`

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Add base and relative pointer to compiler context

src/jsonschema/compile.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/uri_resolve_from_test.cc
=> Add a `resolve_from_if_absolute` method helper to URI

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> In Draft7, `$ref` takes precedence over any other keyword

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc
=> In Draft6, `$ref` takes precedence over any other keyword

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> In Draft4, `$ref` takes precedence over any other keyword

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc
=> In Draft3, `$ref` takes precedence over any other keyword

src/jsonschema/default_compiler_2020_12.h, src/jsonschema/default_compiler_draft4.h
=> Simplify default namespaces in default schema compiler

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Generalize the compiler recursion to perform arbitrary jumps

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonpointer/jsonpointer_to_uri_test.cc
=> Extend JSON Pointer `to_uri` to take a base URI

src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Fix children/condition ordering in logical compiler steps

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Fix schema compiler recursion to follow pointer on the root resource

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Implement basic `$ref` support for Draft 4

src/jsonschema/compile.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Extend schema compiler recursion case to select instance location

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Implement `properties` for Draft 4

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Simplify the Draft 4 compiler for the `allOf` keyword

src/jsonschema/compile_evaluate.cc
=> Simplify schema compiler evaluator

src/jsonschema/compile_evaluate.cc
=> Keep a context long-lived object during schema evaluation

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h
In the assert() - The function in this PR asserts to false, I guess its intended to be true always as per other examples.
=> Corrected some typos

.github/workflows/ci.yml, .github/workflows/website-build.yml
See: https://github.com/sourcemeta/jsontoolkit/pull/564
=> Run CI on fork PRs

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Extend the schema compiler to support annotations

src/jsonschema/compile_evaluate.cc
=> Rename `TargetVisitor` to `TargetInstanceVisitor`

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Represent schema compiler targets with a pair of type/pointer

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_json_test.cc
=> Add a templated instance schema compiler target type

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Implement property loops in the schema compiler

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Implement a schema compiler "regex" assertion

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Implement support for `pattern` in Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Implement a mechanism to reference templated properties

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Support passing custom targets when making assertions with `make<>`

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Unify how we treat compiler values in assertion/annotations

src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Add `keyword_location` to compiler loop steps

src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Add a target to logical schema compiler steps

src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Unify logical and loop compiler step definitions

src/jsonschema/compile_json.cc
=> Support JSON encoding on template property targets

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Support templated annotation values in the schema compiler

src/jsonschema/compile_evaluate.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Report annotation values in the evaluation callback

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Implement a way to push a pointer into another pointer

src/jsonschema/compile.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_2020_12_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Turn step `evaluation_path` into a relative schema location

src/jsonschema/compile.cc
=> Assert that every keyword location is actually valid

src/jsonschema/CMakeLists.txt, src/jsonschema/compile.cc, src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Move internal schema compiler helpers into a private header

src/jsonschema/compile.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_2020_12_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Prepare the compiler to dynamically compute instance locations

src/jsonschema/compile_helpers.h, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Make `relativeInstanceLocation` actually report relative locations

src/jsonschema/compile_helpers.h, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Fix and test instance locations on schema compiler 

src/jsonschema/compile_evaluate.cc
=> Hire evaluation context templates behind a nice interface

src/jsonschema/compile_helpers.h
=> Improve helper to instantiate value-oriented compiler steps

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, test/jsonpointer/jsonpointer_token_test.cc
=> Implement a method to convert a Pointer token into a JSON document

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Improve and simplify how schema compiler loops work

test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Test schema compiler annotation values in traces

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `SchemaBasename` compiler target type

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Implement a method to get the initial part of a pointer

src/jsonschema/compile_evaluate.cc
=> Properly handle schema location when applying compiler loops

src/jsonschema/compile_evaluate.cc
=> Report correct instance location after applying annotation

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_json_test.cc
=> Support an instance parent target type in the compiler

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Implement Draft 4 `patternProperties`

src/jsonschema/compile_evaluate.cc
=> Store annotations using a JSON array in the evaluator

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/jsonschema/compile_evaluate.cc, test/json/json_array_test.cc
=> Implement a `push_back_if_unique` JSON helper

src/jsonschema/compile_evaluate.cc
=> Simplify schema compiler target/value resolution

src/jsonschema/compile_evaluate.cc
=> Go back to storing annotations as a JSON documents

src/jsonschema/compile_evaluate.cc
=> Fetch compiler step values after evaluating the conditions

src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Declare a `ParentAdjacentAnnotations` schema compiler target type

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `SchemaCompilerAssertionNotContains` step

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Implement `additionalProperties` for Draft 4

src/jsonschema/default_compiler_draft4.h
=> Note down potential optimizations for the Draft 4 compiler

src/jsonschema/compile.cc, src/jsonschema/compile_helpers.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Extend the schema compile context to keep track of marked labels

src/jsonschema/compile_evaluate.cc
=> Keep track of schema compiler control labels during evaluation

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a schema compiler control "jump" step

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Implement the `not` applicator for Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Implement array loops in the schema compiler

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Compiler the object mode of `items` in Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Implement a `SizeGreater` assertion on the schema compiler

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile the array variant of `items` for Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Allow schema compiler applicators to take values

src/jsonschema/compile.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Implement schema compiler array loops starting on a given index

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `additionalItems` for Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile the `oneOf` keyword for Draft 4 

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile the `dependencies` keyword for Draft 4

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_array_test.cc
=> Implement `.is_unique()` for JSON arrays

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/json/json_array_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `uniqueItems` for Draft 4

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `minLength` and `maxLength` for Draft 4

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h
=> Clarify the level of support for each JSON Schema dialect

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `minItems` and `maxItems` for Draft 4

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `minProperties` and `maxProperties` for Draft 4

src/json/include/sourcemeta/jsontoolkit/json_value.h
=> Expose `Integer` and `Real` type aliases on `JSON`

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Extend the compiler to support number comparisons

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_number_test.cc
=> Better addition/increment substraction/decrement support in JSON

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Rename compiler comparison assertions to also check equality

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `maximum` and `minimum` in Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement non-equality comparisons for the schema compiler

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `exclusiveMaximum` and `exclusiveMinimum` in Draft 4

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_number_test.cc
=> Add a `.divisible_by()` method to JSON

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `multipleOf` in Draft 4

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h
=> Organize default compiler Draft 4 declarations

test/jsonschema/CMakeLists.txt, test/jsonschema/officialsuite.cc
=> Start running the official JSON Schema test suite for Draft 4

test/jsonschema/officialsuite.cc
=> Test `maxItems` and `minItems` for Draft 4

test/jsonschema/officialsuite.cc
=> Enable many more JSON Schema Draft 4 tests

test/jsonschema/officialsuite.cc
=> Don't compile schemas on every official JSON Schema suite case

test/jsonschema/officialsuite.cc
=> Improve JSON Schema official test suite test names

test/jsonschema/officialsuite.cc
=> Enable all Draft 4 suites that pass already

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/officialsuite.cc
=> Fix `additionalItems` for Draft 4

src/jsonschema/compile_evaluate.cc, test/jsonschema/officialsuite.cc
=> Fix marking reference labels into the schema evaluator

src/jsonschema/compile_evaluate.cc, test/jsonschema/officialsuite.cc
=> Fix how we compute logical XOR on the schema compiler

src/json/parser.h, test/json/json_parse_test.cc
=> Fix parsing 64-bit in JSON on MSVC

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_number_test.cc, test/jsonschema/officialsuite.cc
=> Improve reliability of JSON `.divisible_by()`

test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Test framing schemas that reference their own metaschemas

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc
=> Fix bundling directly-recursive schemas

src/jsonschema/official_resolver.in.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_official_resolver_test.cc
=> Extend official schema resolver to take canonicalized forms

src/jsonschema/bundle.cc, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Canonicalize reference URIs during framing

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/officialsuite.cc
=> Optimize compiling Draft 4 schema with multiple self-references

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc
=> Properly support bundling anonymous schemas

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/uri_fragment_test.cc
=> Add a method to check whether a URI consists only in a fragment

src/jsonschema/anchor.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, src/jsonschema/reference.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_anchor_2020_12_test.cc, test/jsonschema/jsonschema_anchor_draft4_test.cc, test/jsonschema/jsonschema_anchor_draft6_test.cc, test/jsonschema/jsonschema_anchor_draft7_test.cc, unikraft/Makefile.uk
=> Consider pre 2019-09 location independent identifiers as anchors

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Support pre-2019-09 location independent identifiers when framing

test/jsonschema/officialsuite.cc
=> Setup Draft 4 optional test suites

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/officialsuite.cc
=> Implement Draft 4 "ipv4" format support

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/officialsuite.cc
=> Support the `uri` format in Draft 4

src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Optimize compiler conditions on Draft 4 `required`

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_keyword_iterator_test.cc
=> Optimize compiler conditions on Draft 4 `properties`

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Optimize compiler conditions on Draft 4 `uniqueItems`

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Optimize compiler conditions on Draft 4 bound-related keywords

src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Optimize compiler conditions on Draft 4 for `pattern` and `format`

src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc
=> Optimize compiler conditions on Draft 4 for `dependencies`

.github/workflows/ci.yml
=> Remove Ubuntu GitHub Actions Clang workaround

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/json.cc, src/json/stringify.h, test/json/json_prettify_test.cc, test/json/json_stringify_test.cc
Fixes: https://github.com/sourcemeta/jsontoolkit/issues/709
=> Support a comparison function when stringifying/prettifying JSON

src/json/include/sourcemeta/jsontoolkit/json.h
=> Fix new `stringify`/`prettify` ordering examples

cmake/FindUriParser.cmake
=> Only install `uriparser` if JSON Toolkit is being installed

CMakeLists.txt
=> Only generate CMake config files if installation is enabled

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_rule.h, src/jsonschema/transform_rule.cc, test/jsonschema/jsonschema_transform_rule_test.cc, test/jsonschema/jsonschema_transform_rules.h
=> Support optional messages in schema transformation rules

src/jsonschema/compile_json.cc
=> Refactor and simplify encoding schema compiler templates as JSON

src/jsonschema/CMakeLists.txt, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_draft6_test.cc, unikraft/Makefile.uk
=> Compile `const` for Draft 6

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Fix JSON Schema evaluation callback docs

src/jsonschema/compile.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Fix assertion error when compiling Draft 4 metaschema

.github/workflows/ci.yml, test/jsonschema/jsonschema_transform_rules.h
=> Upgrade ClangFormat to v18.1.5

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend schema frame entries with a type enumeration

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Revise how we compile the `type` Draft 4 keyword

src/jsonschema/compile_evaluate.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/officialsuite.cc
=> Pass a reference to the instance in the schema evaluate callback

Makefile.uk, src/jsonschema/CMakeLists.txt, src/jsonschema/compile_describe.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Add a helper to get error messages during schema evaluation

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Introduce an internal container schema compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Emit a single evaluation trace per keyword

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_metaschema_test.cc, unikraft/Makefile.uk
=> Implement a function to obtain the metaschema of a schema

src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/rules/single_type_array.h, src/jsonschema/transform_bundle.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_lint_2019_09_test.cc, test/jsonschema/jsonschema_lint_2020_12_test.cc, test/jsonschema/jsonschema_lint_draft0_test.cc, test/jsonschema/jsonschema_lint_draft1_test.cc, test/jsonschema/jsonschema_lint_draft2_test.cc, test/jsonschema/jsonschema_lint_draft3_test.cc, test/jsonschema/jsonschema_lint_draft4_test.cc, test/jsonschema/jsonschema_lint_draft6_test.cc, test/jsonschema/jsonschema_lint_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h, unikraft/Makefile.uk
=> Flag `type` set to an array of a single element as a lint issue

src/jsonschema/CMakeLists.txt, src/jsonschema/rules/content_media_type_without_encoding.h, src/jsonschema/rules/content_schema_without_media_type.h, src/jsonschema/transform_bundle.cc, test/jsonschema/jsonschema_lint_2019_09_test.cc, test/jsonschema/jsonschema_lint_2020_12_test.cc, test/jsonschema/jsonschema_lint_draft7_test.cc
=> Add linter rules cover `contentMediaType`

src/jsonschema/CMakeLists.txt, src/jsonschema/rules/else_without_if.h, src/jsonschema/rules/then_without_if.h, src/jsonschema/transform_bundle.cc, test/jsonschema/jsonschema_lint_2019_09_test.cc, test/jsonschema/jsonschema_lint_2020_12_test.cc, test/jsonschema/jsonschema_lint_draft7_test.cc
=> Lint that `then` and `else` are redundant without `if`

.github/workflows/ci.yml, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Compile `exclusiveMinimum` and `exclusiveMaximum` for Draft 6

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `SchemaCompilerLoopContains` step

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Compile `contains` for Draft 6

src/jsonschema/compile_evaluate.cc
=> Add a mutable target type to the schema compiler evaluation context

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Introduce a `SchemaCompilerLoopKeys` compiler step

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h
=> Fix function casing in Draft 6 default compiler

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Compile `propertyNames` for Draft 6

test/jsonschema/officialsuite.cc
=> Handle exceptions in the JSON Schema official suite runner

src/jsonschema/default_compiler.cc
=> Register Draft 6 keywords that behave the same as in Draft 4

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, test/json/json_number_test.cc
=> Implement `JSON::is_integer_real` and `JSON::as_integer`

CMakeLists.txt
=> Downgrade CMake requirement to v3.16

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h
=> Consider `contains` as an applicator keyword in Draft 6

src/jsonschema/default_compiler_draft4.h
=> Perform better schema checks in Draft 4 compiler

src/jsonschema/default_compiler_draft4.h
=> Make the compiler permissible with integer reals on Draft 4

.github/workflows/ci.yml
=> Re-enable Windows builds on GitHub Actions

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Compile the `type` keyword for Draft 6

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc
=> Fix bundling a schema without an id that has a relative ref

test/jsonschema/officialsuite.cc
=> Run the JSON Schema Official Test Suite for Draft 6

.github/workflows/ci.yml, .gitignore, Brewfile, vendorpull.mask
=> Make use of Noa as a GitHub Action to setup project

src/jsonschema/default_compiler.cc
=> Register Draft 7 keywords from Draft 4 and Draft 6

vendorpull.mask
=> Do not pass the JSON Schema test suite to consumers

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a "try" logical schema compiler step

src/jsonschema/CMakeLists.txt, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft7.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_draft7_test.cc, unikraft/Makefile.uk
=> Implement `if`/`then`/`else` for Draft 7

test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Exercise Draft 6 and Draft 7 metaschemas on the compiler

test/jsonschema/officialsuite.cc
=> Register Draft 7 remotes from the JSON Schema Official Test Suite

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Fix framing anonymous schemas with embedded resources
