include/jsontoolkit/json/rapidjson/write.h, test/json_write_test.cc
=> Fix crash on .assign() with move semantics

include/jsontoolkit/json/rapidjson/read.h, test/json/json_read_test.cc
C++ otherwise considers the call ambiguous between `std::int64_t` and
`std::nullptr_t`.
=> Support from() when passing a zero literal

README.markdown, include/jsontoolkit/json/iterators.h, test/json/json_iterators_test.cc
Fixes: https://github.com/sourcemeta/jsontoolkit/issues/49
=> Add easy-to-use range-based for loop support

README.markdown, contrib/jsonschema-walker/walker.cc, include/jsontoolkit/jsonschema.h, include/jsontoolkit/jsonschema/walker.h, src/jsonschema.cc, src/jsonschema/walker.cc, test/contrib/example-2020-12-subschemas.txt, test/contrib/example-2020-12.json, test/jsonschema/jsonschema_walker_test.cc
To account for bundled schemas with different vocabularies in use within
the same top-level schema.
=> Check vocabularies at every step in `subschema_iterator()`

include/jsontoolkit/json/rapidjson/read.h, test/json/json_read_test.cc
=> Take small enough `std::uint64_t` as input in `from()`

.github/workflows/ci.yml, test/jsonschema/jsonschema_walker_test.cc
=> Run `clang_format_test`, not `clang_format` on CI

README.markdown, src/json/include/jsontoolkit/json/read.h, test/json/json_read_test.cc
=> Implement a `copy()` function for JSON containers

README.markdown, src/json/include/jsontoolkit/json/read.h, test/json/json_read_test.cc
=> Add a `copy()` overload to duplicate entire containers

src/jsonschema/include/jsontoolkit/jsonschema.h
=> Handle "None" schema walker strategy on the `switch` case

cmake/rapidjson.cmake
=> Fix `JSONTOOLKIT_BACKEND_PATH` empty conditional logic

src/json/CMakeLists.txt, src/jsonschema/CMakeLists.txt
=> Use underscores in library output names

contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/walker.cc, contrib/minify/minify.cc, contrib/prettify/prettify.cc
=> Quiet `argv` pointer ClangTidy warnings until we are in C++20

CMakeLists.txt
=> Set `JSONTOOLKIT_BACKEND_PATH` to be of type `PATH`

contrib/jsonschema_keywords/main.cc, contrib/jsonschema_walker/walker.cc, src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_default_walker.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_default_walker_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Use `std::map` instead of `std::unordered_map` in JSON Schema

src/json/include/sourcemeta/jsontoolkit/json_error.h
=> Allow `ParseError` to be exported on Windows

Makefile
=> Remove obsolete Makefile ctest comment

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Implement a `.back()` method for JSON Pointer

src/json/include/sourcemeta/jsontoolkit/json_array.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h
While GCC and Clang gracefully ignore the declarations, MSVC complains.
=> Avoid exporting templated classes

src/json/parser.h
=> Fix MSVC out of range debug warning when parsing unicode symbols

src/json/parser.h
=> Fix `Traits::eof()` on JSON parser in older GCC versions

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_id_test.cc, test/jsonschema/jsonschema_official_resolver_test.cc
=> Make `id()` taker a resolver and a default dialect

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h
=> Return a `string_view` when fetching the id of a `SchemaResolutionError`

src/jsonschema/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_id_2019_09_test.cc, test/jsonschema/jsonschema_id_2020_12_test.cc, test/jsonschema/jsonschema_id_draft0_test.cc, test/jsonschema/jsonschema_id_draft1_test.cc, test/jsonschema/jsonschema_id_draft2_test.cc, test/jsonschema/jsonschema_id_draft3_test.cc, test/jsonschema/jsonschema_id_draft4_test.cc, test/jsonschema/jsonschema_id_draft6_test.cc, test/jsonschema/jsonschema_id_draft7_test.cc, test/jsonschema/jsonschema_id_test.cc
=> Properly test `id()` across dialects

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, test/jsonpointer/jsonpointer_pointer_test.cc, test/jsonpointer/jsonpointer_token_test.cc
=> Overload the `<` operator for `Pointer`

src/jsonschema/CMakeLists.txt, src/jsonschema/anchor.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_anchor_2019_09_test.cc, test/jsonschema/jsonschema_anchor_2020_12_test.cc
=> Implement an `anchors()` function similar to `id()`

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Make Pointer's `pop_back()` throw on empty pointers

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Store the top-level schema id on `frame()` entries

src/jsonschema/anchor.cc, test/jsonschema/jsonschema_anchor_2019_09_test.cc, test/jsonschema/jsonschema_anchor_2020_12_test.cc
=> Gracefully take boolean schemas in `anchors()`

src/jsonschema/reference.cc
=> Simplify `id()` ternary logic in `frame()`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Turn `ReferenceFrame` into a proper class

test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Exercise `frame()` when passing an explicit equal default id

src/jsonschema/reference.cc
=> Clarify that in `frame()`, found identifiers only may be relative

src/uri/include/sourcemeta/jsontoolkit/uri.h
=> Clarify that `URI::recompose` doesn't really normalize

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc
=> Perform URI canonicalization on `ReferenceFrame::defines`

src/jsonschema/reference.cc
=> Add an assertion to confirm there is one base dialect only in `frame()`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Rename `base()` to `root()` in `ReferenceFrame`

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/referencingsuite.cc
=> Extend `.frame()` to receive `ReferenceMap` argument

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Don't record plain reference frames on schemas with ids

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Simplify `ReferenceMap` to only consider static references

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/referencingsuite.cc
=> Avoid passing a separate `ReferenceFrame` for dynamic frames

contrib/jsonschema_frame/main.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend `ReferenceMap` to split URI by its potential fragment

src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference_type.h
=> Extract `ReferenceType` to its own header

src/jsonschema/anchor.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_anchor_2019_09_test.cc, test/jsonschema/jsonschema_anchor_2020_12_test.cc
=> Add an overload for `anchors()` that directly take vocabularies

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, src/jsonschema/reference.cc
=> Add performance-friendly `vocabularies()` overloads

src/jsonschema/reference.cc, src/jsonschema/reference_frame.cc, test/jsonschema/jsonschema_frame_test.cc
=> Simplify `ReferenceFrame::defines` to not canonicalize

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
=> Generalize transformer `into_object()` as `replace()`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
=> Generalize transformer `.replace()` to take pointers

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transformer.h, src/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
=> Generalize transformer `.assign()` to take base pointers

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_integer_test.cc
=> Fix GCC taking `initializer_list` precedence over copy-constructor

src/uri/include/sourcemeta/jsontoolkit/uri.h
=> Fix "Escape" typo in URI docs

vendorpull.mask
=> Mask `FindGoogleTest.cmake` by default

src/uri/include/sourcemeta/jsontoolkit/uri.h
=> Fix `URI::path()` example

src/uri/uri.cc
=> Fix Windows MSVC assert where `.front()` fails on empty strings

src/jsonschema/compile.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_2020_12_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Add `absoluteKeywordLocation` to compiler steps

src/json/include/sourcemeta/jsontoolkit/json_value.h
The right function name is now `parse`. There used to be a `parse_json`
one before.
See: https://github.com/sourcemeta/jsontoolkit/discussions/561
=> Fix JSON docs that reference `parse_json`

CMakeLists.txt
This is the one that Ubuntu 22.04 LTS has at the moment.
=> Downgrade CMake minimum version to 3.22

src/jsonschema/compile_evaluate.cc
=> Rename `target_instance` to `target_value` in schema evaluator

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Add a `Pointer::pop_back` overload to pop many tokens

src/jsonschema/default_compiler_draft4.h
=> Handle evaluation paths correctly in Draft `$ref`

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Pass the evaluate path on the schema compiler evaluation callback

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc
=> Rename the `Basename` compiler target type to `InstanceBasename`

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Remove unnecessary `SchemaBasename` compiler target type

test/jsonschema/jsonschema_frame_2020_12_test.cc, test/uri/uri_canonicalize_test.cc, test/uri/uri_recompose_test.cc
=> Make sure empty fragment references are framed correctly

src/jsonschema/compile.cc
=> Canonicalize URIs when compiling subschemas in the schema compiler

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile `anyOf` for Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `SchemaCompilerAssertionSizeLess` step

src/json/include/sourcemeta/jsontoolkit/json_array.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_value_test.cc
Sadly we needed to be super explicit. We cannot default given we often
deal with incomplete types, and the spaceship operator won't work the
same across objects and arrays.
See: https://github.com/sourcemeta/jsontoolkit/issues/509
=> Support every comparison operator in the JSON class

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_value_test.cc
=> Fix JSON `>` operator to not accidentally behave as `>=`

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_number_test.cc
=> Implement `.as_real()` in JSON to reduce casting logic

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_value_test.cc, test/jsonschema/officialsuite.cc, test/jsonschema/referencingsuite.cc
=> Workaround JSON class member initializer lists inconsistencies in MSVC

src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_parse_test.cc, test/jsonschema/officialsuite.cc
=> Make string `.size()` report logical size and introduce `.byte_size()`

cmake/CompilerOptions.cmake
=> Enable `/MP` for faster MSVC builds

src/jsonpointer/stringify.h, test/jsonpointer/jsonpointer_to_uri_test.cc, test/jsonschema/officialsuite.cc
=> Fix JSON Pointer double quotes and backslashes on URI fragment encodings

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Optimize `enum` with a single choice on the schema compiler

doxygen/index.markdown
Probably better to mention it as part of the `find_package` section, as
that how you would actually consume it.
=> Revise how we promote Homebrew on the documentation

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Rename `SchemaCompilerValue` to `SchemaCompilerStepValue`

src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform_bundle.h, src/jsonschema/rules/max_contains_without_contains.h, src/jsonschema/rules/min_contains_without_contains.h, src/jsonschema/transform_bundle.cc, test/jsonschema/jsonschema_lint_2019_09_test.cc, test/jsonschema/jsonschema_lint_2020_12_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Lint that `maxContains` and `minContains` are redundant without `contains`

src/jsonschema/CMakeLists.txt, src/jsonschema/rules/unevaluated_items_default.h, src/jsonschema/rules/unevaluated_properties_default.h, src/jsonschema/transform_bundle.cc, test/jsonschema/jsonschema_lint_2019_09_test.cc, test/jsonschema/jsonschema_lint_2020_12_test.cc
=> Lint `unevaluated*` keywords when set to their logical defaults

src/json/json_value.cc, test/json/json_number_test.cc
=> Fix `JSON::is_integer_real()` to not crash on non-numeric instances

.github/workflows/ci.yml
See: https://github.com/actions/runner-images/issues/10004
See: https://github.com/google/googletest/issues/4556
=> Disable Windows runners for now given GitHub Actions incident

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Fix describe statement for `SchemaCompilerAssertionEqual`

src/jsonschema/compile_evaluate.cc
=> Fix `SchemaCompilerLogicalTry` break on exhaustive mode

src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Fix crash when using a nested `propertyNames` in Draft 6 and 7

src/jsonschema/compile_evaluate.cc
=> Never continue on `SchemaCompilerInternalContainer` on failure

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Get rid of the `SchemaCompilerAnnotationPrivate` step

test/jsonschema/jsonschema_test_utils.h
=> Fix typo on `EVALUATE_WITH_TRACE_EXHAUSTIVE_FAILURE` test macro

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft6.h
=> Fix `LoopContains` compiler step with min/max bounds

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Avoid running `additionalItems` when `items` covers all items pre 2019-09

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Rename `NoAnnotation` to `NoAdjacentAnnotation` in the compiler

src/jsonschema/compile_evaluate.cc
=> Better template types for `EvaluationContext::resolve_value`

src/jsonschema/compile_evaluate.cc
=> Add an `InstanceAnnotations` type alias on `EvaluationContext`

src/jsonschema/compile_evaluate.cc
=> Accept empty keyword sets in `SchemaCompilerInternalNoAnnotation`

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Fix `items` not producing correct positional annotations in 2019-09

src/json/json_value.cc
=> Avoid copying array contents on JSON `unique()`

src/jsonschema/explain.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_explain.h, test/jsonschema/jsonschema_explain_string_test.cc
=> Rename `SchemaExplainer` instances to `SchemaExplanation`

src/jsonschema/compile_evaluate.cc
=> Never allow checking cousing annotations on the evaluator

src/jsonpointer/jsonpointer.cc, src/jsonschema/default_compiler_2019_09.h
=> Fix incorrect type checking on `unevaluatedItems`

src/jsonschema/default_compiler_draft4.h
=> Add a minor note to optimize `$ref` on non-recursive schemas

src/uri/uri.cc
One of the next thing is to reduce the coupling we have with `uriparser`. On the end (before replacing the parser) we should be able to put all the coupling in the `parse` method.
This PR is one of this!
=> refactor(uri): avoid using uriparser internals

src/jsonschema/default_compiler.cc
=> Handle `dependencies` in 2020-12 for backwards compatibility

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc
=> Fix walker to make `unevaluatedItems` depend on `contains` on 2020-12

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Let `SchemaCompilerValueRange` be configured to run exhaustively

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h
We'll address minor differences in there to avoid unnecessary code
duplication.
=> Make `unevaluatedItems` in 2020-12 point to 2019-09

src/jsonschema/jsonschema.cc, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_identify_2019_09_test.cc, test/jsonschema/jsonschema_identify_2020_12_test.cc, test/jsonschema/jsonschema_identify_draft0_test.cc, test/jsonschema/jsonschema_identify_draft1_test.cc, test/jsonschema/jsonschema_identify_draft2_test.cc, test/jsonschema/jsonschema_identify_draft3_test.cc, test/jsonschema/jsonschema_identify_draft4_test.cc, test/jsonschema/jsonschema_identify_draft6_test.cc, test/jsonschema/jsonschema_identify_draft7_test.cc
=> Better handle `$id`/`id` with sibling `$ref` in `identify()`

test/jsonschema/jsonschema_test_utils.h
=> Fix argument ordering in `EVALUATE_TRACE_POST_DESCRIBE`

test/jsonschema/jsonschema_compile_draft6_test.cc
=> Add missing `const` "describe" tests for Draft 6

src/uri/uri.cc, test/uri/uri_normalize_test.cc
=> test(uri): add more normalize tests

benchmark/jsonschema/compiler_basic.cc
=> Avoid `BENCHMARK_MAIN` as we are already linking to `benchmark::benchmark_main`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe cases of unsatisfiable `minContains`/`maxContains`

Makefile
=> Remove unused `KRAFT` variable from the `Makefile`

benchmark/jsonschema/CMakeLists.txt
=> Use Noa default options for benchmark executables

benchmark/CMakeLists.txt, benchmark/jsonschema/CMakeLists.txt, benchmark/jsonschema_compiler.cc, benchmark/jsonschema_validator.cc
This will make it more practical to adopt
https://github.com/benchmark-action/github-action-benchmark. We can
still focus on specific subcomponents by either omitting the ones we
don't want at the CMake options level, or with `--benchmark_filter`.
=> Create a single Google Benchmark executable

benchmark/CMakeLists.txt
=> Get rid of weird trailing spaces in `benchmark/CMakeLists.txt`

src/jsonschema/default_compiler_draft4.h
=> Reduce `maximum`/`minimum` conditions from 3 steps to 1

src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Optimize `maximum` and `minimum` conditions if there is `type`

.github/workflows/ci.yml
=> Fix benchmark names in the GitHub Actions matrix

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Don't unnecessarily emit `properties` annotations in the "optimized" mode

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Implement a new `LoopPropertiesNoAdjacentAnnotation` compile step

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h
=> Simplify `unevaluatedItems` instruction wrapping

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Start generalizing `LoopItemsFromAnnotationIndex` as `LoopItemsUnevaluated`

src/jsonschema/default_compiler_draft6.h
=> Remove unnecessary conditions for `exclusive(Max|min)imum` on Draft 6

src/jsonschema/compile_evaluate.cc
=> Simplify `resolve_target` in the `EvaluationContext`

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_test_utils.h
=> Implement a new `AnnotationWhenArraySizeEqual` compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_test_utils.h
=> Implement a new `AnnotationWhenArraySizeGreater` compiler step

src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Compile out assertions that would never run anyway

src/jsonschema/compile.cc, src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_2020_12.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_template_format_test.cc
=> Remove the idea of explicit conditions from the compiler

src/jsonschema/compile_evaluate.cc
=> Get rid of `EvaluationContext::push` overload

src/jsonschema/compile_evaluate.cc
=> Simplify annotation-related types in `EvaluationContext`

src/jsonschema/compile_evaluate.cc
=> Try a vector for keeping track of annotation blacklists

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Prefer vector over sets when configuring compiler steps

src/json/json_value.cc
=> Use `.find()` instead of `.at()` to access JSON object values

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_pointer_test.cc
=> Add helpers to directly push properties and indexes to pointers

test/jsonpointer/jsonpointer_walker_test.cc
=> Make JSON Pointer object walker tests independent of key ordering

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Use an `std::unordered_map` for compiler values

src/jsonschema/trace.h
=> Correctly compile `trace.h` on macOS on GCC

test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Make compiler 2019-09 object tests independent of ordering

src/jsonschema/compile_describe.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Don't mark `$ref` destination on non-recursive cases

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Prefer unrolling `properties` for a small amount of optional subschemas

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Introduce a new `LoopPropertiesType(Strict)` compiler step

src/jsonschema/compile.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve error when making a `$ref` to a non-schema

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Introduce a new `SchemaCompilerAssertionTypeObjectBounded`

src/evaluator/CMakeLists.txt, src/evaluator/context.cc, src/evaluator/context.h, src/evaluator/evaluator.cc
=> Internally split `EvaluationContext` into its own file

benchmark/CMakeLists.txt, benchmark/validator_helper.cc, src/evaluator/context.cc, src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator.h, test/evaluator/evaluator_test.cc
=> Support reusing the `EvaluationContext` across evaluation runs

src/evaluator/evaluator.cc
=> Remove unnecessary `break` statements in the evaluator

src/evaluator/context.cc, src/uri/uri.cc
According to clang tidy:
```cpp
/Users/tonygo/oss/jsontoolkit/src/evaluator/context.cc:74:33: error: std::move of the variable 'new_instance' of 
the trivially-copyable type 'std::reference_wrapper<const JSON>' has no effect; remove std::move() 
[performance-move-const-arg,-warnings-as-errors]
```
=> refactor(jsonschema/uri): remove useless std::move

src/jsonschema/default_compiler_draft4.h
This is possible since any matching groups will not be exposed in the final schema and might make matching slightly more efficient.
=> Use the `nosubs` option to `std::regex`

src/jsonpointer/jsonpointer.cc, src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc, test/jsonpointer/jsonpointer_try_get_test.cc
=> Don't assume the instance is an object when unrolling `properties`

src/jsonschema/default_compiler.cc, src/jsonschema/default_walker.cc, test/evaluator/evaluator_2019_09_test.cc, test/evaluator/evaluator_2020_12_test.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
JSON Schema actually defines it for backwards compatibility reasons.
Kudos to @michaelmior for catching this.
=> Support `definitions` in 2019-09 and 2020-12

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, test/json/json_parse_test.cc
There are cases in which we want to check the logical size of a string
according to the JSON grammar without turning the string into a JSON
document (for performance reasons).
=> Extract JSON string logical size method as `static`

src/evaluator/context.cc, src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h
=> Avoid JSON allocations when handling `propertyNames`

src/evaluator/include/sourcemeta/jsontoolkit/evaluator_value.h
=> Try `unordered_set` in `SchemaCompilerValuePropertyFilter`

src/evaluator/include/sourcemeta/jsontoolkit/evaluator_value.h
This reverts commit eac12e205eeef700a734a661a683de15d869527f.
=> Revert "Try `unordered_set` in `SchemaCompilerValuePropertyFilter` (#1255)"

src/evaluator/context.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h
=> Remove unused annotation logic from `EvaluationContext`

src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Prioritize smaller subschemas when unrolling `properties`

src/jsonschema/walker.cc
=> refactor(walker): use std::ranges:sort instead of std::sort

src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Always unroll `properties` under `oneOf`

src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Don't apply `additionalProperties` type optimization in exhaustive mode

src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Only apply type bounds optimizations on `FastValidation` mode

src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Don't collapse `properties` with only `type` on exhaustive mode

src/jsonschema/compile_helpers.h
=> Correctly proxy compiler mode on `make` compiler helpers

src/jsonschema/compile.cc, test/evaluator/CMakeLists.txt, test/evaluator/evaluator_2019_09_test.cc, test/evaluator/evaluator_2020_12_test.cc, test/evaluator/evaluator_draft4_test.cc
=> Propertly detect presence of `unevaluated*` keywords

src/evaluator/evaluator.cc, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h
=> Don't rely on `exhaustive` flag for `LogicalOr`

src/evaluator/evaluator.cc
=> Don't consider exhausive evaluation on `LogicalNot`

.github/workflows/ci.yml
=> Fix ClangFormat installation on Linux

src/evaluator/include/sourcemeta/jsontoolkit/evaluator.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_error.h, src/json/include/sourcemeta/jsontoolkit/json.h, src/json/include/sourcemeta/jsontoolkit/json_error.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/jsonl/include/sourcemeta/jsontoolkit/jsonl.h, src/jsonl/include/sourcemeta/jsontoolkit/jsonl_iterator.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_error.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/include/sourcemeta/jsontoolkit/uri_error.h
=> Guard export includes in every public header

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Keep a list of all possible schema resources during compilation

src/evaluator/context.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/compile.cc, src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_json_test.cc
=> Emit step schema resources as hashes

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/compile_describe.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Rename `LogicalNot` to `AnnotationNot`

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_starts_with_initial_test.cc
=> Implement `starts_with_initial` for `GenericPointer`

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_starts_with_test.cc
=> Implement a JSON Pointer `starts_with` variant that takes a token tail

src/uri/uri.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/uri/uri_canonicalize_test.cc
=> Correctly canonicalize relative URIs that do not begin with `/`

test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Test framing with relative base identifiers

src/json/include/sourcemeta/jsontoolkit/json_object.h
=> Keep `ObjectKeyHash` available for clients even on older GCC

src/regex/include/sourcemeta/jsontoolkit/regex.h, src/regex/regex.cc, test/regex/regex_matches_test.cc
=> Extend `Regex` to support non-full regex evaluation

src/json/parser.h
=> Add safety value assertions to parser pre/post callbacks

src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/json_value.cc, test/json/json_object_test.cc
=> Introduce a `.find()` method for JSON objects

src/uri/uri.cc
This is minor, the way URL canonicalization is currently written, it's possible that the implementation will access a character past the end of the string.
=> Fix string overrun in URL canonicalization

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/jsonpointer_weakpointer_test.cc
Fixes: https://github.com/sourcemeta/jsontoolkit/issues/1362
=> Extend `to_pointer` to convert weak pointers to non-weak pointers

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, test/json/json_object_test.cc
=> Implement a `.defines()` JSON overload that takes a property hash

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h
=> Flatten `Token` to not contain a variant at all

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h
=> Don't rehash properties when pushing `Pointer` to `WeakPointer`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend `.frame()` to collect inbound references

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Improve walker types to distinguish in-place applicators

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Revise `SchemaWalkerStrategy` to make space for non-applicator types

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Extend `SchemaWalkerResult` to include the origin vocabulary

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_unevaluated.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/unevaluated.cc, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc, test/jsonschema/jsonschema_unevaluated_2020_12_test.cc
=> Analyse adjacent schemas for `unevaluated(Properties|Items)`

src/jsonschema/unevaluated.cc, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc
=> Fix traversal of nested schema resources in `unevaluated()`

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_unevaluated_2020_12_test.cc
=> Fix `if` not affecting `unevaluated(Properties|Items)` evaluation

src/jsonschema/unevaluated.cc, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc
=> Ensure `unevaluated` accounts for `additionalItems` without `items`

src/jsonschema/CMakeLists.txt, src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_keywords.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/unevaluated.cc, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Extract `SchemaWalkerStrategy` as `KeywordType`

src/jsonschema/bundle.cc, src/jsonschema/frame.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_frame.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_unevaluated.h, src/jsonschema/resolver.cc, src/jsonschema/unevaluated.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc, test/jsonschema/jsonschema_unevaluated_2020_12_test.cc, test/jsonschema/referencingsuite.cc
=> Turn schema framing into a class

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Return found identifiers in `FlatFileSchemaResolver`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Simplify re-identification in `FlatFileSchemaResolver`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Implement a `.reidentify()` method on `FlatFileSchemaResolver`

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_identify_2019_09_test.cc, test/jsonschema/jsonschema_identify_2020_12_test.cc, test/jsonschema/jsonschema_identify_draft3_test.cc, test/jsonschema/jsonschema_identify_draft4_test.cc, test/jsonschema/jsonschema_identify_draft6_test.cc, test/jsonschema/jsonschema_identify_draft7_test.cc
=> Throw an exception when re-identifying and `$ref` overrides `($)id`

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_identify_draft3_test.cc, test/jsonschema/jsonschema_identify_draft4_test.cc, test/jsonschema/jsonschema_identify_draft6_test.cc, test/jsonschema/jsonschema_identify_draft7_test.cc
=> Make `reidentify()` work even with top-level `$ref`

src/uri/uri.cc, test/uri/uri_relative_to_test.cc
=> Support `relative_to` on URNs

src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/relativize.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_relativize_test.cc
=> Implement a function to turn absolute schema references into relative

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc, test/jsonschema/schemas/2020-12-absolute-ref.json
=> Ensure `FlatFileSchemaResolver` enforces relative references

src/jsonschema/relativize.cc, src/uri/uri.cc, test/jsonpointer/jsonpointer_to_uri_test.cc, test/jsonschema/jsonschema_relativize_test.cc, test/uri/uri_canonicalize_test.cc
=> Fix `relativize()` mistreating relative references with `..`

src/jsonschema/CMakeLists.txt, src/jsonschema/bundle.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_bundle.h, src/jsonschema/unidentify.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc, test/jsonschema/jsonschema_bundle_test.cc, test/jsonschema/jsonschema_unidentify_test.cc
=> Extract `BundleOptions::WithoutIdentifiers` into its own `unidentify()`

src/uri/uri.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/uri/uri_canonicalize_test.cc, test/uri/uri_resolve_from_test.cc
=> Fix canonicalization of relative URI paths with leading slashes

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, test/json/json_string_test.cc
=> Implement a `.contains()` method for JSON strings

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h
=> Fix `default_schema_walker` typos in documentation

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Improve how `FlatFileSchemaResolver` abstracts reading files

src/jsonschema/relativize.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc, test/jsonschema/jsonschema_relativize_test.cc, test/jsonschema/schemas/2019-09-recursive-ref.json
=> Fix `FlatFileSchemaResolver` messing up `$recursiveRef`

vendorpull.mask
=> Mask GoogleTest and GoogleBenchmark on `vendorpull`

DEPENDENCIES, src/json/json_value.cc, vendor/noa/src/flat_map/include/sourcemeta/noa/flat_map.h
=> Optimise `try_at` in JSON

src/json/include/sourcemeta/jsontoolkit/json_hash.h, test/json/json_hash_test.cc
=> Make use of `__uint128_t` if available for `KeyHash`

src/core/json/CMakeLists.txt, src/core/json/include/sourcemeta/core/json_object.h
=> Stop consuming `FlatMap` from Noa

CMakeLists.txt
=> Fix `CMAKE_MODULE_PATH` append when including the project

README.markdown
=> Simplify README even more

CMakeLists.txt, cmake/Sourcemeta.cmake
=> Modify parent's `CMAKE_MODULE_PATH`

src/core/json/include/sourcemeta/core/json_object.h
=> Support old Clang versions

src/core/json/include/sourcemeta/core/json.h, src/core/json/include/sourcemeta/core/json_error.h, src/core/json/json.cc, src/core/json/parser.h, src/core/jsonl/include/sourcemeta/core/jsonl.h, src/core/jsonl/iterator.cc, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_error.h, src/core/yaml/yaml.cc, test/json/json_error_test.cc, test/json/json_parse_error_test.cc, test/json/jsontestsuite.cc, test/jsonl/jsonl_parse_error_test.cc, test/jsonpointer/jsonpointer_parse_error_test.cc
=> Namespace JSON-related errors

test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Test `SchemaFlatFileResolver` re-identifying a schema with absolute refs

src/core/jsonschema/include/sourcemeta/core/jsonschema_resolver.h, src/core/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Allow `SchemaFlatFileResolver` to take a custom reference visitor

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/stringify.h, test/jsonpointer/jsonpointer_template_test.cc
=> Make `PointerTemplate` distinguish between property/item/key wildcards

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/official_walker.cc, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Revise `SchemaKeywordType` for 2020-12 applicators

src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Make schema walkers report instance location pointer templates

src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, test/jsonschema/jsonschema_test_utils.h
=> Rename `instance_location` to `relative_instance_location` in `SchemaIteratorEntry`

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc
=> Fix `destination_of` on subschemas that are also resources

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc
=> Account for orphaned anchors in framing

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Populate `destination_of` on anchors during framing

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, test/jsonpointer/jsonpointer_template_test.cc
=> Implement a `.concat` move method on `PointerTemplate`

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Fix instance locations framing calculations

test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Ensure `SchemaIterator` fully records orphan pointer templates

src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend `SchemaIteratorEntry` to report parent schemas

src/core/jsonschema/frame.cc
=> Rename `traverse_instance_locations` internal helper to a better name

benchmark/jsonschema.cc, src/core/jsonschema/bundle.cc, src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, src/core/jsonschema/jsonschema.cc, src/core/jsonschema/resolver.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/referencingsuite.cc
=> Fix broken instance locations on orphan parent schemas

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc
=> Don't depend on `destination_of` for framing instance locations

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Correctly repopulate anchor instance locations after references

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend `SchemaFrame::references_to` to support dynamic references

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonschema/frame.cc, test/jsonpointer/jsonpointer_template_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Fix `$dynamicRef` unresolved framed instance locations

src/core/json/include/sourcemeta/core/json.h, src/core/json/json.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_resolver.h, src/core/jsonschema/resolver.cc, test/json/json_parse_callback_test.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
This PR refactors the `read_json` function to accept an optional `ParseCallback` parameter, enhancing the flexibility of JSON parsing. It also updates related function calls and definitions to align with this change as discussed in [slack](https://json-schema.slack.com/archives/C8C4UBXDF/p1739193378870919?thread_ts=1738590781.293879&cid=C8C4UBXDF)
=> Refactor read_json to accept optioal callback and update related tests and functions

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/official_walker.cc, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Extend schema walker to account for conditional instance locations

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonschema/frame.cc, test/jsonpointer/jsonpointer_template_test.cc
=> Implement `PointerTemplate::conditional_of` to loosely compare templates

src/core/yaml/include/sourcemeta/core/yaml.h, src/core/yaml/yaml.cc, test/yaml/yaml_parse_test.cc
=> Overload `parse_yaml` to read from `std::basic_istream`

cmake/FindBoostRegex.cmake
=> Only install Boost Regex headers on `sourcemeta_core_dev`

src/core/yaml/yaml.cc, test/yaml/yaml_parse_test.cc
See: https://github.com/sourcemeta/jsonschema/issues/241
=> Improve YAML parsing of quoted numbers

src/core/json/json.cc
See: https://github.com/sourcemeta/jsonschema/issues/252
=> Fix `read_file` on Bash's process substitution

cmake/common/defaults.cmake
=> Document why we don't enable LTO on `RelWithDebInfo`

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, test/jsonpointer/jsonpointer_template_test.cc
=> Rename `PointerTemplate::conditional_of` to `matches`

src/core/regex/include/sourcemeta/core/regex.h, test/regex/regex_matches_test.cc
=> Implement a `Regex::matches_if_valid` convenience shorthand

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, test/jsonpointer/jsonpointer_template_test.cc
=> Add wildcard support for `PointerTemplate::matches`

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, test/jsonpointer/jsonpointer_template_test.cc
=> Improve `PointerTemplate` wildcard matching for tokens and regexes

test/jsonpointer/jsonpointer_template_test.cc
=> Test `PointerTemplate` conditional wildcards with `matches`

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, test/jsonpointer/jsonpointer_template_test.cc
=> Implement a `PointerTemplate::trivial` method

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/stringify.h, src/core/jsonschema/walker.cc, test/jsonpointer/jsonpointer_template_test.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Suffix `PointerTemplate` conditionals with keyword names

src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h
=> Add a TODO item for supporting unfixable lint checks

src/core/jsonschema/include/sourcemeta/core/jsonschema.h
=> Clarify that `unidentify()` might lead to invalid schemas

src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_wrap_test.cc
=> Fix `wrap()` to always include schema identifiers

src/core/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_test.cc
=> Improve bundling-related invalid JSON errors

src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_test.cc
=> Offer a way to query the mode of a `SchemaFrame`

src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_wrap_test.cc
See: https://github.com/sourcemeta/jsonschema/issues/304#issuecomment-2814383860
=> Don't enforce `wrap()` URIs to be absolute (they could be relative)

src/core/jsonschema/bundle.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema.h, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc
=> Support passing a custom default container to `bundle`

src/core/json/include/sourcemeta/core/json.h, src/core/json/include/sourcemeta/core/json_error.h, src/core/json/include/sourcemeta/core/json_object.h, src/core/json/include/sourcemeta/core/json_value.h, src/core/json/json.cc, src/core/json/json_value.cc, src/core/json/parser.h, src/core/json/stringify.h
Reported by clang-tidy check `misc-include-cleaner` 
Refs: https://github.com/sourcemeta/blaze/issues/429
=> style(clang-tidy): Clean include headers of src/core/json

src/core/jsonl/include/sourcemeta/core/jsonl.h, src/core/jsonl/include/sourcemeta/core/jsonl_iterator.h, src/core/jsonl/iterator.cc, src/core/jsonl/jsonl.cc
Reported by clang-tidy check misc-include-cleaner
Refs: https://github.com/sourcemeta/blaze/issues/429
=> Include clean src core jsonl

src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_pointer.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_position.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_subpointer_walker.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_token.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_walker.h, src/core/jsonpointer/jsonpointer.cc, src/core/jsonpointer/parser.h, src/core/jsonpointer/position.cc, src/core/jsonpointer/stringify.h, test/jsonpointer/jsonpointer_error_test.cc, test/jsonpointer/jsonpointer_parse_error_test.cc, test/jsonpointer/jsonpointer_position_test.cc, test/jsonpointer/jsonpointer_token_test.cc, test/jsonpointer/jsonpointer_weakpointer_test.cc
Reported by clang-tidy check misc-include-cleaner
Refs: sourcemeta/blaze#429
=> style(clang-tidy): Clean include headers of src/core/jsonpointer

cmake/common/targets/clang-tidy.config
See: https://github.com/sourcemeta/core/pull/1650#issuecomment-2906062409
=> Disable `MissingIncludes` in ClangTidy

src/core/json/include/sourcemeta/core/json_value.h, src/core/json/json_value.cc, test/json/json_object_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1694
=> Implement a `JSON::at_or` method for objects

src/core/json/include/sourcemeta/core/json_value.h, src/core/json/json_value.cc, test/json/json_string_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1696
=> Implement a `JSON::trim` method for trimming strings

src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_empty_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1712
=> Implement a `URI::empty` method for checking if URIs are empty

src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_metaschema_test.cc
See: https://github.com/sourcemeta/core/commit/483b23ce7dcf1c3d182fbb54607984b3cd83c8a7#r160222217
=> Throw `SchemaUnknownDialectError` in `metaschema()`

src/core/json/json_value.cc, src/core/uri/uri.cc
=> style(clang-tidy): fix cppcoreguidelines init variables

src/core/jsonschema/frame.cc, src/core/jsonschema/jsonschema.cc, src/core/uri/uri.cc, src/core/yaml/yaml.cc
=> style(clang-tidy): fix misc-use-anonymous-namespace

src/extension/alterschema/CMakeLists.txt, src/extension/alterschema/alterschema.cc, src/extension/alterschema/linter/unnecessary_allof_ref_wrapper.h, test/alterschema/alterschema_lint_2019_09_test.cc, test/alterschema/alterschema_lint_2020_12_test.cc, test/alterschema/alterschema_lint_draft4_test.cc, test/alterschema/alterschema_lint_draft6_test.cc, test/alterschema/alterschema_lint_draft7_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1737
=> Lint unnecessary `allOf` wrappers for `$ref` in 2019-09 and later

.github/workflows/ci.yml, cmake/common/targets/clang-format.cmake
=> Attempt to install ClangFormat binaries using CMake

src/extension/alterschema/alterschema.cc
=> style(clang-tidy): fix misc-internal-linkage errors

cmake/common/targets/clang-tidy.config
closes #1677
This doesn't understand the usage of parameter inside the function. The check is similar to the -Wunused-parameter compiler diagnostic. => This doesn't add much value but noise.
=> style(clang-tidy): disable `misc-unused-parameters`

src/core/jsonl/include/sourcemeta/core/jsonl_iterator.h, src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_resolver.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_walker.h, src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc
=> style(clang-tidy): fix cppcoreguidelines-pro-type-member-init errors

src/core/json/json.cc, src/core/yaml/yaml.cc
=> style(clang-tidy): Supress cppcoreguidelines-avoid-non-const-global-variables

src/core/jsonschema/frame.cc
Two reports were about struct. We are suppressing them for now. Let's revisit when it creates noice on actual functions.
=> style(clang-tidy): fix bugprone-exception-escape

cmake/common/targets/clang-tidy.config
closes #1675
Mostly reporting false positives, creating noise.
The check doesn't notice the modification after initialization properly.
=> style(clang-tidy): Disable `misc-const-correctness`

src/core/json/include/sourcemeta/core/json_value.h, src/core/json/json_value.cc, src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc
=> style(clang-tidy): Fix `cppcoreguidelines-noexcept-move-operations` errors

src/core/json/include/sourcemeta/core/json_value.h
Reported with #1754
Refs #1657
=> style(clang-tidy): fix `bugprone-return-const-ref-from-parameter`

src/core/uri/uri.cc, test/uri/uri_resolve_from_test.cc
=> Fix `URI::resolve_from` when dealing with file bases

.vscode/settings.json, src/extension/alterschema/CMakeLists.txt, src/extension/alterschema/alterschema.cc, src/extension/alterschema/linter/multiple_of_default.h, test/alterschema/alterschema_lint_2019_09_test.cc, test/alterschema/alterschema_lint_2020_12_test.cc, test/alterschema/alterschema_lint_draft4_test.cc, test/alterschema/alterschema_lint_draft6_test.cc, test/alterschema/alterschema_lint_draft7_test.cc
**Rule ID**: multiple_of_default
**Description**: "Setting multipleOf to 1 does not add any further constraint"
**Condition**: Detects multipleOf: 1 (integer) or multipleOf: 1.0 (real) in JSON Schema objects
**Transform**: Removes the redundant multipleOf property
**Dialects**: Supports draft4, draft6, draft7, 2019-09, and 2020-12
- Registered the rule in the Readability mode (not common rules) since it removes redundant default values
- Properly categorized alongside other Default rules like AdditionalPropertiesDefault
- Comprehensive Test Coverage: Added 16 test cases across all supported JSON Schema drafts:
Positive cases: multipleOf: 1 and multipleOf: 1.0 removal
Negative cases: No change for non-1 values (multipleOf: 2, multipleOf: 0.5)
Edge cases: String values ("1"), zero (0), …
=> Linter: add rule to remove default multipleOf: 1

src/extension/alterschema/linter/unnecessary_allof_ref_wrapper.h, test/alterschema/alterschema_lint_2020_12_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1826
=> Update `allOf` in-place when removing artificial `$ref` wrappers

src/core/json/include/sourcemeta/core/json_value.h, src/core/json/json_value.cc, test/json/json_array_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1834
=> Implement a `JSON::erase_if` method for arrays

src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h, test/jsonschema/jsonschema_transformer_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1836
=> Add `const` iterators to `SchemaTransformer`

cmake/common/clang-tidy.cmake
C++ Standard flag is available in the compilation database.
=> Remove redundant cxx standard

src/core/json/include/sourcemeta/core/json_auto.h, test/json/json_auto_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1851
=> Support `unsigned long long` in `to_json()`

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_position.h, src/core/jsonpointer/position.cc, test/jsonpointer/jsonpointer_position_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1854
=> Extend `PointerPositionTracker` with a `to_json` method

src/extension/alterschema/linter/unnecessary_allof_wrapper_draft.h, src/extension/alterschema/linter/unnecessary_allof_wrapper_modern.h, test/alterschema/alterschema_lint_2019_09_test.cc, test/alterschema/alterschema_lint_2020_12_test.cc, test/alterschema/alterschema_lint_draft4_test.cc, test/alterschema/alterschema_lint_draft6_test.cc, test/alterschema/alterschema_lint_draft7_test.cc
=> Fix `unnecessary_allof_wrapper_modern` conflict on canonicalise

src/core/jsonschema/jsonschema.cc
=> Throw `SchemaRelativeMetaschemaResolutionError` on `metaschema()`

test/uri/uri_recompose_test.cc
=> Test that `URI::recompose()` won't unescape URI paths

src/extension/build/adapter_filesystem.cc, src/extension/build/include/sourcemeta/core/build_adapter_filesystem.h
=> Make `BuildAdapterFilesystem::mark` thread safe

test/uri/uri_extension_test.cc
=> Test `URI::extension` on a URI with an empty fragment

src/core/json/json_value.cc
=> Fix segfault when running `JSON::unique()` on different threads

test/schemaconfig/schemaconfig_from_json_test.cc
=> Guarantee backwards compatibility in `SchemaConfig`
