test/jsonschema/officialsuite.cc
=> Run official Draft 7 tests against the schema compiler

src/jsonschema/bundle.cc, src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_bundle.h, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc, test/jsonschema/jsonschema_bundle_test.cc
=> Introduce the idea of modifier options for JSON Schema bundling

src/jsonschema/bundle.cc, src/jsonschema/compile.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Throw on unresolved schema references during bundle/compile

src/jsonschema/bundle.cc, src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Introduce a new `SchemaReferenceError` error

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_user_info_test.cc
=> feat(uri): add `user_info()` API

src/json/include/sourcemeta/jsontoolkit/json_error.h, test/json/json_error_test.cc
=> Improve generic `ParseError` message

README.markdown
=> Showcase Bowtie badges on the repo

src/jsonschema/bundle.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_bundle.h, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc
See: https://github.com/asyncapi/spec-json-schemas/issues/550
=> Support performing JSON Schema bundling without identifiers

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc
=> Re-do framing without identifiers as a step after framing

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc
=> Fix bundling without identifiers on boolean subschemas

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h
=> Template Draft 4 `properties`/`patternProperties` to make them usable on 2019-09

test/jsonschema/jsonschema_test_utils.h
=> Extend schema compiler test utils to assert on public annotations

src/jsonschema/bundle.cc, src/jsonschema/jsonschema.cc
=> Improve schema resolution error messages

src/jsonschema/default_compiler.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_test.cc, unikraft/Makefile.uk
=> Introduce a new `SchemaVocabularyError`

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_test.cc
=> Improve how bundling reacts to invalid schema targets

src/json/include/sourcemeta/jsontoolkit/json_error.h, src/json/json.cc, test/json/json_parse_error_test.cc
=> Improve error reporting of `from_file()`

README.markdown
=> Update Bowtie badges

src/jsonschema/compile.cc, src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Split the schema compiler context into static & dynamic parts

src/jsonschema/compile_evaluate.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/officialsuite.cc
=> Extend the schema evaluation callback with a phase type enum

src/jsonschema/compile_evaluate.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Also invoke the evaluation callback before processing a step

src/jsonschema/default_compiler.cc
=> Register 2019-09 backwards-compatible keywords in the compiler

.github/workflows/ci.yml
=> Remove Windows MSVC GitHub Actions workaround

DEPENDENCIES, vendor/noa/cmake/noa/defaults.cmake
=> Enable IPO/LTO

src/jsonschema/bundle.cc, src/jsonschema/reference.cc, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Inline non-official metaschemas when performing bundling

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Add range support to `SchemaCompilerLoopContains`

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_test_utils.h, unikraft/Makefile.uk
=> Test `properties` for 2019-09

README.markdown
Fixes https://github.com/sourcemeta/jsontoolkit/issues/336
=> Add a demonstrative Example

src/jsonschema/CMakeLists.txt, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Implement `dependentRequired` for 2019-09

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2019_09.h
=> Add skeleton for implementing remaining 2019-09 keywords

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Implement `additionalProperties` for 2019-09

src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_template_format_test.cc, unikraft/Makefile.uk
=> Implement a format comparison for printing compiler templates

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile `dependentSchemas` for 2019-09

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile `contains`, `minContains`, and `maxContains` for 2019-09

test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Test that metadata/content keywords don't produce annotations before 2019-09

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile metadata keywords in 2019-09

test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Test content vocabulary keywords in 2019-09

test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Test compiling unknown keywords in Draft 4, 6, 7, and 2019-09

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `SizeEqual` schema compiler step

src/jsonschema/default_compiler_draft4.h
=> Refactor how `items` is compiled for Draft 4, 6, and 7

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile `items` for JSON Schema 2019-09

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile `additionalItems` for 2019-09

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `ParentAnnotations` compiler target type

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement an `InternalNoAnnotation` compiler step

src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile `unevaluatedProperties` for 2019-09

src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Serialize compiler step new "data" fields

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement an `Annotations` target type for the compiler

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a `SchemaCompilerLoopItemsFromAnnotationIndex` step

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Compile `unevaluatedItems` for 2019-09

src/jsonschema/anchor.cc, test/jsonschema/jsonschema_anchor_2019_09_test.cc
=> Extend `.anchors()` to consider `$recursiveAnchor`

test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Better test frame entry types

test/jsonschema/jsonschema_frame_2019_09_test.cc
=> Test `$recursiveAnchor` when framing 2019-09

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/json.cc, test/json/json_parse_test.cc
=> Expose file reading logic as a JSON function

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Remove unnecessary `properties` compiler condition

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_id_2019_09_test.cc, test/jsonschema/jsonschema_id_2020_12_test.cc, test/jsonschema/jsonschema_id_draft0_test.cc, test/jsonschema/jsonschema_id_draft1_test.cc, test/jsonschema/jsonschema_id_draft2_test.cc, test/jsonschema/jsonschema_id_draft3_test.cc, test/jsonschema/jsonschema_id_draft4_test.cc, test/jsonschema/jsonschema_id_draft6_test.cc, test/jsonschema/jsonschema_id_draft7_test.cc, test/jsonschema/jsonschema_id_test.cc
=> Supported a more relaxed schema identification strategy

src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_id_test.cc
=> Make loose schema id resolution work even on unresolvable dialects

src/jsonschema/jsonschema.cc
=> Refactor internal schema identification logic

src/jsonschema/bundle.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_identify_2019_09_test.cc, test/jsonschema/jsonschema_identify_2020_12_test.cc, test/jsonschema/jsonschema_identify_draft0_test.cc, test/jsonschema/jsonschema_identify_draft1_test.cc, test/jsonschema/jsonschema_identify_draft2_test.cc, test/jsonschema/jsonschema_identify_draft3_test.cc, test/jsonschema/jsonschema_identify_draft4_test.cc, test/jsonschema/jsonschema_identify_draft6_test.cc, test/jsonschema/jsonschema_identify_draft7_test.cc, test/jsonschema/jsonschema_identify_test.cc
=> Implement a method to anonymize a schema

src/jsonschema/bundle.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_bundle_test.cc, test/jsonschema/jsonschema_identify_2019_09_test.cc, test/jsonschema/jsonschema_identify_2020_12_test.cc, test/jsonschema/jsonschema_identify_draft0_test.cc, test/jsonschema/jsonschema_identify_draft1_test.cc, test/jsonschema/jsonschema_identify_draft2_test.cc, test/jsonschema/jsonschema_identify_draft3_test.cc, test/jsonschema/jsonschema_identify_draft4_test.cc, test/jsonschema/jsonschema_identify_draft6_test.cc, test/jsonschema/jsonschema_identify_draft7_test.cc, test/jsonschema/jsonschema_identify_test.cc
=> Implement a schema `reidentify()` set of functions

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_test.cc
=> Fix JSON Schema bundling error case around invalid schemas

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_relative_to_test.cc, unikraft/Makefile.uk
=> Introduce a method to get a relative URI out of absolute ones

src/uri/uri.cc, test/uri/uri_relative_to_test.cc
=> Fix `relative_to` treating hosts as paths

Makefile.uk, src/jsonschema/CMakeLists.txt, src/jsonschema/explain.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_explain.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_explain_string_test.cc, unikraft/Makefile.uk
=> Introduce a new function to analyze and explain a schema

vendorpull.mask
=> Mask benchmark files by default

src/jsonschema/explain.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_explain.h, test/jsonschema/jsonschema_explain_string_test.cc
=> Take a badges approach to explanation constraints

src/jsonschema/explain.cc, test/jsonschema/jsonschema_explain_string_test.cc
=> Support explaining `minLength` and `maxLength` on strings

src/jsonschema/explain.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_explain.h, test/jsonschema/jsonschema_explain_string_test.cc
=> Make minor adjustments to string explanations

src/jsonschema/explain.cc
=> Refactor schema explainer

src/jsonschema/explain.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_explain.h, test/jsonschema/jsonschema_explain_string_test.cc
=> Define scalar explanation examples as JSON

src/jsonschema/explain.cc, test/jsonschema/jsonschema_explain_string_test.cc
=> Add basic format handler on string explainer

src/jsonschema/explain.cc, test/jsonschema/jsonschema_explain_string_test.cc
=> Print format name after the type in explainer

src/jsonschema/explain.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_explain.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_explain_enumeration_test.cc, test/jsonschema/jsonschema_explain_string_test.cc, test/jsonschema/jsonschema_test_utils.h, unikraft/Makefile.uk
=> Support explaining enumeration schemas

src/jsonschema/default_compiler.cc, test/jsonschema/officialsuite.cc, vendor/jsonschema-test-suite.mask, vendor/jsonschema-test-suite/remotes/different-id-ref-string.json, vendor/jsonschema-test-suite/remotes/draft2019-09/baseUriChange/folderInteger.json, vendor/jsonschema-test-suite/remotes/draft2019-09/baseUriChangeFolder/folderInteger.json, vendor/jsonschema-test-suite/remotes/draft2019-09/baseUriChangeFolderInSubschema/folderInteger.json, vendor/jsonschema-test-suite/remotes/draft2019-09/dependentRequired.json, vendor/jsonschema-test-suite/remotes/draft2019-09/detached-ref.json, vendor/jsonschema-test-suite/remotes/draft2019-09/extendible-dynamic-ref.json, vendor/jsonschema-test-suite/remotes/draft2019-09/ignore-prefixItems.json, vendor/jsonschema-test-suite/remotes/draft2019-09/integer.json, vendor/jsonschema-test-suite/remotes/draft2019-09/locationIndependentIdentifier.json, vendor/jsonschema-test-suite/remotes/draft2019-09/metaschema-no-validation.json, vendor/jsonschema-test-suite/remotes/draft2019-09/metaschema-optional-vocabulary.json, vendor/jsonschema-test-suite/remotes/draft2019-09/name-defs.json, vendor/jsonschema-test-suite/remotes/draft2019-09/nested/foo-ref-string.json, vendor/jsonschema-test-suite/remotes/draft2019-09/nested/string.json, vendor/jsonschema-test-suite/remotes/draft2019-09/ref-and-defs.json, vendor/jsonschema-test-suite/remotes/draft2019-09/subSchemas.json, vendor/jsonschema-test-suite/remotes/draft2019-09/tree.json, vendor/jsonschema-test-suite/remotes/nested-absolute-ref-to-string.json, vendor/jsonschema-test-suite/remotes/urn-ref-string.json
=> Enable all 2019-09 tests that already pass

src/jsonschema/reference.cc, test/jsonschema/officialsuite.cc
=> Make `refOfUnknownKeyword` 2019-09 test pass

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h, test/jsonschema/officialsuite.cc
=> Make `minContains` and `maxContains` 2019-09 tests pass

src/jsonschema/compile_evaluate.cc
=> Do not consider annotations inside `not` in 2019-09

test/jsonschema/officialsuite.cc
=> Enable the 2019-09 `not` suite

src/jsonpointer/jsonpointer.cc, src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc
=> Support `$recursiveRef` when framing schemas

src/jsonschema/default_compiler_2019_09.h
=> Handle `$recursiveRef` as `$ref` in 2019-09

src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Report schema resources on compiler steps

src/jsonschema/compile_evaluate.cc
=> Use an `std::stack` for `frame_sizes` on the schema evaluator

src/jsonschema/compile.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Keep track of whether a schema requires dynamic scoping or not

src/jsonschema/compile_evaluate.cc
=> Maintain a stack of schema resources in the evaluation context

src/jsonschema/compile.cc
=> Prepare compiler for prepending steps to final compiler templates

src/jsonschema/compile_helpers.h
=> Fix inaccurate comment in `compile_helpers.h`

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Add a new compiler step to mark but not execute templates

src/jsonschema/compile.cc
=> Precompile dynamic anchors and prepend them to compiler templates

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a dynamic anchor jump step for `$recursiveRef`

src/jsonschema/compile_evaluate.cc, test/jsonschema/officialsuite.cc
=> Enable all remaining 2019-09 official required tests

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h
=> Remove outdated JSON Schema version matrix documentation

src/jsonschema/compile_evaluate.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Fix schema resources after-evaluation assertion

src/jsonschema/compile.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Add more tests for `$recursiveRef` on 2019-09

src/jsonschema/compile.cc
=> Only attempt to precompile dynamic anchors on 2019-09

README.markdown
=> Add 2019-09 Bowtie support badge to the README

src/jsonschema/CMakeLists.txt, src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Scaffold the compiler skeleton for 2020-12 support

src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h
=> Reduce duplication when compiling JSON Schema keywords

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Compile `prefixItems` and `items` for 2020-12

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h
=> Remove 2020-12 `unevaluatedProperties` scaffold

test/jsonschema/officialsuite.cc, vendor/jsonschema-test-suite.mask, vendor/jsonschema-test-suite/remotes/draft2020-12/baseUriChange/folderInteger.json, vendor/jsonschema-test-suite/remotes/draft2020-12/baseUriChangeFolder/folderInteger.json, vendor/jsonschema-test-suite/remotes/draft2020-12/baseUriChangeFolderInSubschema/folderInteger.json, vendor/jsonschema-test-suite/remotes/draft2020-12/detached-dynamicref.json, vendor/jsonschema-test-suite/remotes/draft2020-12/detached-ref.json, vendor/jsonschema-test-suite/remotes/draft2020-12/extendible-dynamic-ref.json, vendor/jsonschema-test-suite/remotes/draft2020-12/format-assertion-false.json, vendor/jsonschema-test-suite/remotes/draft2020-12/format-assertion-true.json, vendor/jsonschema-test-suite/remotes/draft2020-12/integer.json, vendor/jsonschema-test-suite/remotes/draft2020-12/locationIndependentIdentifier.json, vendor/jsonschema-test-suite/remotes/draft2020-12/metaschema-no-validation.json, vendor/jsonschema-test-suite/remotes/draft2020-12/metaschema-optional-vocabulary.json, vendor/jsonschema-test-suite/remotes/draft2020-12/name-defs.json, vendor/jsonschema-test-suite/remotes/draft2020-12/nested/foo-ref-string.json, vendor/jsonschema-test-suite/remotes/draft2020-12/nested/string.json, vendor/jsonschema-test-suite/remotes/draft2020-12/prefixItems.json, vendor/jsonschema-test-suite/remotes/draft2020-12/ref-and-defs.json, vendor/jsonschema-test-suite/remotes/draft2020-12/subSchemas.json, vendor/jsonschema-test-suite/remotes/draft2020-12/tree.json
=> Enable `cross-draft` tests on Draft 7 and 2019-09

test/jsonschema/officialsuite.cc
=> Run many of the 2020-12 tests that already pass

src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_2020_12.h, test/jsonschema/officialsuite.cc
=> Compile `contains` without annotations for 2020-12

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Compile a starting version of `contains` for 2020-12

src/jsonschema/default_compiler_2019_09.h, test/jsonschema/officialsuite.cc
=> Compile `unevaluatedProperties` for 2020-12

src/jsonschema/default_compiler_2019_09.h
=> Compile `unevaluatedItems` for 2020-12

src/jsonschema/default_compiler_draft4.h, test/jsonschema/officialsuite.cc
=> Fix incorrect compile conditions for `additionalItems`/`items`

src/jsonschema/compile_evaluate.cc
=> Don't consider broken `$recursiveAnchor` chains

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc
=> Fix framing anchors on relative identifiers

src/jsonschema/reference.cc
=> Simplify `$dynamicRef` framing logic

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Better frame cases where `$dynamicRef` behaves as `$ref` in 2020-12

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Support `$ref` to `$dynamicAnchor` in 2020-12

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2020_12.h
=> Compile `$dynamicRef` that behaves as `$ref` in 2020-12

src/jsonschema/compile_json.cc, test/jsonschema/jsonschema_template_format_test.cc
=> Fix schema compiler template JSON formatter

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Error when compiling references coming from unknown keywords

src/jsonschema/compile.cc, src/jsonschema/default_compiler_2020_12.h, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/officialsuite.cc
=> Handle `$dynamicRef` only containing URI fragments

test/uri/uri_resolve_from_test.cc
=> test(uri): add few RFC 3986 tests for resolve

src/jsonschema/compile_evaluate.cc
=> Simplify schema resource management during evaluation

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2020_12.h, test/jsonschema/officialsuite.cc
=> Enable `$dynamicRef` 2020-12 official tests

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/officialsuite.cc
=> Extend `describe()` to take more information for better messages

README.markdown
=> Add JSON Schema 2020-12 badge to the README

README.markdown
=> Fix little typo on README example

src/jsonschema/compile_evaluate.cc
=> Detect type "any" instructions with a single type

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Improve type checking describe messages

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve description of "type any" steps

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve descriptions of `SchemaCompilerAssertionDefines`

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve descriptions of `SchemaCompilerAssertionDefinesAll`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve description of `SchemaCompilerAssertionRegex`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve description of `SchemaCompilerLogicalAnd` for `allOf`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe the `properties` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Better describe the `const` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Better describe the `if` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Better describe the `multipleOf` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Better describe the `then` and `else` keywords

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Minor corrections to `allOf` describe keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe `exclusiveMinimum` and `exclusiveMaximum`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe the `contains` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe the `minLength` and `maxLength` keywords

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe the `propertyNames` keyword

README.markdown
=> Showcase basic schema evaluation in the README

src/jsonl/iterator.cc, test/jsonl/jsonl_parse_error_test.cc, test/jsonl/jsonl_parse_test.cc
=> Gracefully handle parsing empty JSONL documents

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe `properties` annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Better describe `patternProperties`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `additionalProperties` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `not` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe `additionalItems` and `items`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Better describe the `$dynamicRef` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Better describe `items` annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Better describe `prefixItems` annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Better describe `contains` annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe meta-data annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe content related annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe `unevaluatedProperties`/`unevaluatedItems` annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe `items`/`additionalItems` annotations on 2019-09

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc
=> Better describe unknown keyword annotations

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe the `dependentRequired` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe the `$recursiveRef` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe `unevaluatedProperties`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `unevaluatedItems` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `minimum` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe the `dependentSchemas` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `maximum` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `minItems` and `maxItems` keywords

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe `minProperties` and `maxProperties`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `uniqueItems` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `anyOf` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `enum` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `oneOf` keyword

src/jsonschema/compile_describe.cc
=> Refactor most step descriptions

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Treat the `SizeEqual` assertion as internal

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_test.cc
=> Better describe `additionalProperties` set to `false`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Better describe `unevaluatedProperties` set to `false`

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `format` keyword

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Make sure the tense of step descriptions are consistent

src/jsonschema/compile_describe.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better describe the `dependencies` keyword

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_output_error_trace_test.cc
=> Introduce a basic schema evaluation stack trace reporter

src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_is_ipv6_test.cc, test/uri/uri_is_mailto_test.cc, test/uri/uri_parse_test.cc, test/uri/uri_path_test.cc
I extracted a few tests from `uriparser`
=> test(uri): add more parsing tests

src/jsonschema/compile.cc, src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_2020_12.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_compile_template_draft4_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Introduce the concept of internal compiler steps

CMakeLists.txt, benchmark/jsonschema/CMakeLists.txt, benchmark/jsonschema/validator.cc
=> Kickstart schema validation benchmark cases

src/jsonschema/compile_evaluate.cc
=> Don't emit evaluation callbacks if the callback is a no-op

.github/workflows/ci.yml, benchmark/CMakeLists.txt
=> Add a benchmark target that outputs Google Benchmark JSON

.github/workflows/ci.yml
=> Don't run Google Benchmark on sanitizer jobs

.github/workflows/ci.yml
=> Introduce automated benchmark comparisons

.github/workflows/ci.yml
=> Use nicer OS names on benchmark results

benchmark/CMakeLists.txt, benchmark/validator_helper.cc, src/jsonschema/CMakeLists.txt, src/jsonschema/compile_evaluate.cc, src/jsonschema/trace.h
=> Introduce basic tracing facilities for schema evaluation

src/jsonschema/compile_evaluate.cc
=> Fix how we end the annotation emit trace

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_keyword_iterator_test.cc
=> Walk `properties` after `required` from Draft 4 on-wards

src/jsonschema/compile_evaluate.cc, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Always break early from "and" operations in the evaluator

benchmark/jsonschema_validator.cc, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_template_draft4_test.cc
=> Optimize compilation of required schema properties

.github/workflows/ci.yml
Otherwise we seem to only get one comment on PRs for the run that
finished last.
=> Give different platforms different benchmark names

benchmark/validator_helper.cc
=> Print nanoseconds in the validation profile helper

.github/workflows/ci.yml
Otherwise we get a massive stream of comments on every PR
=> Only benchmark static builds

src/jsonschema/compile_evaluate.cc
=> Optimize how we determine instance location on target resolution

src/jsonschema/compile_evaluate.cc
=> Add various pointer-related evaluator optimization TODOs

README.markdown
PREVIEW: https://github.com/sourcemeta/jsontoolkit/tree/impr-rdme
It triggers me when I check the readme this morning!
=> chore: highlights dialect support

src/jsonschema/compile.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc, test/jsonschema/jsonschema_compile_test.cc, test/jsonschema/officialsuite.cc
=> Support performing schema compilation in "optimized" mode

src/jsonschema/compile_json.cc, test/jsonschema/jsonschema_template_format_test.cc
=> Correctly format the new `report` step option

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Avoid unnecessary `patternProperties` annotations in optimized mode

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h
=> Establish implicit preconditions for compiler steps

benchmark/jsonschema_validator.cc
=> Add a benchmark case exercising schema `items` in Draft 4

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h
=> Reduce generated steps for `items` schemas before 2019-09

benchmark/jsonschema_validator.cc
=> Start benchmarking optional schema properties with minimal matches

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_draft4.h
=> Get rid of `AssertionRegex` explicit type conditions

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Introduce a new `LogicalWhenType` step

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_draft4.h
=> Avoid type preconditions on `AssertionDefines` for `required`

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Implement a new `LogicalWhenDefines` compile step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Introduce a new `AnnotationBasenameToParent` compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Introduce a new `LoopPropertiesRegex` compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Add a new `LogicalWhenNoAdjacentAnnotations` compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Implement a new `LogicalWhenAdjacentAnnotations` compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Streamline how we compile `if`/`then`/`else`

src/jsonschema/compile_evaluate.cc
So we can more easily create other compiler rules without duplicating
all of the currently messy logic.
=> Centralise annotation logic on the `EvaluationContext`

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Introduce a new `LoopPropertiesNoAnnotation` compiler step

src/jsonschema/default_compiler_2019_09.h
=> Unwrangle `unevaluatedItems` annotation related instructions

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft7.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft7_test.cc
=> Introduce a new `LoopItemsUnmarked` compiler step

src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Take a mask as part of `LoopItemsUnevaluated`

src/jsonschema/compile.cc, src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_evaluate_test.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_template_format_test.cc
=> Get rid of the concept of compiler target types

src/jsonschema/compile_evaluate.cc
=> Delete `resolve_value` from `EvaluationContext`

src/jsonschema/compile.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_2020_12.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_template_format_test.cc
=> Unify how applicator and control steps are defined

src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft6.h, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Don't evaluate conditions for compiler steps that don't use them

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_evaluate_test.cc
=> Introduce a new `AssertionPropertyDependencies` compiler step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_2020_12.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Introduce a new `LogicalWhenArraySizeGreater` step

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Introduce a new `LogicalWhenArraySizeEqual` compiler step

doxygen/Doxyfile.in, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Improve Doxygen layout for documenting compiler instructions

doxygen/Doxyfile.in, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Improve how detailed description is shown on Doxygen

src/jsonschema/compile_evaluate.cc
=> Create better evaluator step begin/end macros

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonschema/compile_evaluate.cc
=> Attempt to improve Pointer's `push_back` for zero or one tokens

benchmark/jsonschema_validator.cc
=> Add a schema benchmark case of highly nested objects

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/jsonpointer_get_test.cc
=> Add helpers to query a document using a single Pointer token

src/jsonschema/compile_evaluate.cc
=> Keep a reference to the instance on the `EvaluationContext`

src/jsonschema/compile_evaluate.cc
=> Create specialized methods for traversing instances during loops

.github/workflows/ci.yml, .github/workflows/website-build.yml, .github/workflows/website-deploy.yml
=> Upgrade `actions/checkout` due to deprecation warning

src/jsonschema/compile_evaluate.cc
=> Assert that annotation steps have no relative instance location

benchmark/CMakeLists.txt, benchmark/validator_helper.cc
=> Support JSONL input in the benchmark validate helper

src/jsonschema/compile_evaluate.cc
=> Simplify `EvaluationContext::push` signature

src/jsonschema/compile_evaluate.cc
To avoid continuous pointer traversal.
=> Keep a stack of instance references in the evaluator

src/jsonschema/compile_evaluate.cc
=> Refactor how we get the next instance stack entry

src/jsonschema/compile_evaluate.cc
=> Don't bother with `frame_sizes` in `enter`/`leave`

src/jsonschema/compile_evaluate.cc
=> Use a vector to present frame sizes

src/jsonschema/compile_evaluate.cc
=> Optimize how to get null values to evaluation callbacks

src/jsonschema/compile_evaluate.cc
=> Set `noexcept` in a few `EvaluationContext` methods

benchmark/jsonschema_validator.cc
=> More benchmarks for `properties`/`patternProperties`/`additionalProperties`

src/jsonschema/default_compiler.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h
=> Better guard the use of `properties`/`patternProperties` annotations

benchmark/validator_helper.cc, src/jsonschema/compile.cc, src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_2020_12_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc, test/jsonschema/jsonschema_compile_draft7_test.cc, test/jsonschema/jsonschema_compile_test.cc, test/jsonschema/officialsuite.cc
=> Implement a new `LoopPropertiesExcept` instruction

CMakeLists.txt
=> Fix module test order on `CMakeLists.txt`

src/json/include/sourcemeta/jsontoolkit/json_object.h
=> Stop supporting reverse iterators on JSON objects

test/jsonschema/jsonschema_compile_2019_09_test.cc, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Make schema validation object trace tests order independent

src/json/include/sourcemeta/jsontoolkit/json_object.h, test/json/json_value_test.cc
=> Stop supporting ordering on JSON objects

.github/workflows/ci.yml, Brewfile, DEPENDENCIES, vendor/noa/cmake/noa/compiler/options.cmake
=> Run tests on GCC for macOS

.github/workflows/ci.yml
=> Use compiler suffixes for all benchmarked platforms

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, test/jsonschema/jsonschema_walker_test.cc
=> Clarify that schema walkers do not depend on property order

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_walker.h, src/jsonschema/reference.cc
=> Enforce a specific ordering when framing schema pointers

src/jsonschema/compile_describe.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Stop assuming object ordering on the compiler/evaluator

src/json/include/sourcemeta/jsontoolkit/json_object.h
=> Make use of `unordered_map` for JSON objects

benchmark/jsonschema_validator.cc
=> Add a Draft 4 benchmark case that exercises non-recursive `$ref`

src/jsonschema/default_compiler_draft4.h
=> Check static reference labels before unconditionally unrolling

benchmark/validator_helper.cc
=> Measure compile time on `validator_helper.cc`

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Fix static reference cycles between subschemas

src/jsonschema/compile.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Property detect recursion when compiling `$ref`

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Improve compilation speed of highly recursive schemas

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Better handle invalid static references when compiling

src/json/include/sourcemeta/jsontoolkit/json_object.h, test/json/json_array_test.cc, test/json/json_value_test.cc
=> Fix sorting JSON arrays of objects

benchmark/jsonschema_validator.cc
=> Add benchmark case for `patternProperties` with true schemas

test/jsonschema/jsonschema_compile_2019_09_test.cc
=> Test `patternProperties` with wildcard schema on 2019-09

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Optimize `patternProperties` set to wildcard schemas before 2019-09

benchmark/jsonschema_validator.cc
=> Add a new JSON Schema benchmark case for few optional `properties`

benchmark/validator_helper.cc
=> Print the compiled schema in `benchmark/validator_helper.cc`

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Implement new `AssertionPropertyType(Strict)` instructions

src/jsonschema/default_compiler_draft4.h, test/jsonschema/jsonschema_compile_draft4_test.cc
=> Don't emit a wrapper instruction when unrolling `$ref`

benchmark/jsonschema_validator.cc
=> Benchmark a Draft 4 `$ref` to a single property

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/jsonpointer.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_has_test.cc, test/jsonpointer/jsonpointer_weakpointer_test.cc
=> Add a `has` function to check if a document contains a given Pointer

src/jsonschema/compile_evaluate.cc
=> Stop assuming that relative instance locations have up to 1 token

src/jsonschema/compile_evaluate.cc
=> Generalize `AssertionPropertyType` to work on multi-token paths

Brewfile
=> Pull ClangFormat from `pip` on CI

src/jsonschema/compile_json.cc, test/jsonschema/jsonschema_template_format_test.cc
=> Make compiler JSON formatter more resilient to unknown keywords

src/jsonschema/compile_evaluate.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc
First advice taken from the great tidy!
=> refactor: use `std::uint8_t` for enum

benchmark/jsonschema_validator.cc
=> Benchmark `additionalProperties` with only `type` inside

.github/workflows/ci.yml, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, src/jsonl/include/sourcemeta/jsontoolkit/jsonl_iterator.h, src/jsonl/iterator.cc, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/jsonpointer.cc, src/jsonpointer/parser.h, src/jsonpointer/stringify.h, src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, src/jsonschema/jsonschema.cc, src/jsonschema/reference.cc, src/jsonschema/resolver.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Upgrade ClangFormat to v19.1.0

src/jsonschema/compile_evaluate.cc
=> Perform a one-time pointer resolution on `AssertionPropertyType(Strict)`

src/jsonschema/default_compiler_draft4.h
=> Increase threshold for preferring `properties` loop vs unroll

src/jsonschema/compile_describe.cc, src/jsonschema/compile_evaluate.cc, src/jsonschema/compile_helpers.h, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft6.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/jsonschema/jsonschema_compile_draft4_test.cc, test/jsonschema/jsonschema_compile_draft6_test.cc
=> Introduce a new `SchemaCompilerAssertionTypeArrayBounded`

benchmark/CMakeLists.txt, benchmark/json.cc
=> Benchmark JSON uniqueness on arrays of objects

src/jsonschema/compile_evaluate.cc
=> Reduce a bit evaluation macros

src/evaluator/context.cc, src/evaluator/context.h, src/evaluator/evaluator.cc
=> Revise `EvaluationContext` interface to support resetting instances

src/evaluator/CMakeLists.txt, src/evaluator/context.cc, src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h
=> Elevate `EvaluationContext` as part of the public interface

benchmark/validator_helper.cc
=> Print more descriptive failures on validation benchmark helper

benchmark/CMakeLists.txt, benchmark/draft6_adaptivecard.json, benchmark/jsonschema_compiler.cc, src/jsonschema/default_compiler_draft4.h
=> Don't expand reference targets with lots of children references

src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h, test/evaluator/evaluator_draft4_test.cc
=> Improve error when compiling invalid regular expresions

benchmark/jsonschema_validator.cc
=> Benchmark `propertyNames` on Draft 6

benchmark/jsonschema_validator.cc
=> Benchmark `if`/`then`/`else` on Draft 7

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_value.h, src/jsonschema/compile_describe.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft7.h, test/evaluator/evaluator_draft7_test.cc
=> Introduce a new `LogicalCondition` instruction for `if`/`then`/`else`

src/evaluator/context.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h
=> Inline private `annotations` getter from `EvaluationContext`

CMakeLists.txt, README.markdown, doxygen/index.markdown
=> Focus project description on the JSON Schema evaluator

src/jsonschema/default_compiler_draft4.h
=> Refactor how we compile substeps in `properties`

test/evaluator/evaluator_draft4_test.cc
=> Test `oneOf` smart `properties` short-circuit checks

src/json/parser.h, test/json/json_parse_test.cc, test/json/json_string_test.cc
=> Properly parse UTF-16, UTF-32, and surrogate pairs

DEPENDENCIES, vendor/noa/cmake/noa/compiler/options.cmake
=> Upgrade Noa to `3b98a611b647926dd32065c4ac5011a40b5d8b20`

DEPENDENCIES, src/evaluator/CMakeLists.txt, vendor/noa/cmake/noa/compiler/options.cmake
=> Emit loop vectorization diagnostics on the schema evaluator

src/json/stringify.h, test/evaluator/evaluator_draft4_test.cc, test/json/json_stringify_test.cc
=> Fix how JSON integer reals are stringified

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_value.h, src/jsonschema/default_compiler_draft4.h
=> Don't use sets in the evaluator

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/compile.cc, src/jsonschema/compile_helpers.h, src/jsonschema/default_compiler_draft4.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h, test/evaluator/evaluator_2019_09_test.cc, test/evaluator/evaluator_2020_12_test.cc, test/evaluator/evaluator_draft4_test.cc, test/evaluator/evaluator_draft6_test.cc, test/evaluator/evaluator_draft7_test.cc, test/evaluator/evaluator_evaluate_test.cc, test/evaluator/evaluator_test.cc, test/evaluator/evaluator_utils.h, test/evaluator/officialsuite.cc, test/jsonschema/jsonschema_compile_json_test.cc, test/jsonschema/jsonschema_output_error_trace_test.cc
=> Introduce the concept of JSON Schema compiler modes

src/jsonschema/default_compiler_draft4.h, src/jsonschema/default_compiler_draft7.h, test/evaluator/evaluator_draft4_test.cc
=> Don't directly unroll `$ref` in exhaustive mode

src/jsonschema/default_compiler.cc, test/evaluator/evaluator_2019_09_test.cc, test/evaluator/evaluator_2020_12_test.cc, test/evaluator/evaluator_draft4_test.cc
=> Only emit unknown and pure annotation keywords on exhaustive mode

src/jsonschema/compile.cc, src/jsonschema/default_compiler_2019_09.h, src/jsonschema/default_compiler_2020_12.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_compile.h
=> Make conditional applicator annotations depend on the context

src/evaluator/evaluator.cc
=> Fix `LoopPropertiesType` non-strict guard logic

src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_2019_09_test.cc, test/evaluator/evaluator_2020_12_test.cc, test/jsonschema/jsonschema_output_error_trace_test.cc
=> Support expanding `$ref` on 2019-09 and 2020-12

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/default_compiler_draft4.h
=> Don't rely on the `exhaustive` flag for `LogicalXor`

src/evaluator/include/sourcemeta/jsontoolkit/evaluator_value.h
=> Minor improvements to `SchemaCompilerValuePropertyFilter` definition

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/compile_describe.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_2019_09.h, test/evaluator/evaluator_2019_09_test.cc
=> Better group instructions that are annotation related

src/evaluator/context.cc, src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/default_compiler_2019_09.h
=> Revise `EvaluationContext` annotation interface

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_metaschema_test.cc
=> Remove weird blank lines

benchmark/CMakeLists.txt, benchmark/compiler_draft6.cc, benchmark/evaluator_draft4.cc, benchmark/evaluator_draft6.cc, benchmark/evaluator_draft7.cc
=> Re-organize Google Benchmark cases

benchmark/CMakeLists.txt, benchmark/evaluator_2020_12.cc
=> Add a `$dynamicRef` benchmark case

src/evaluator/context.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_context.h, src/jsonschema/compile.cc, src/jsonschema/default_compiler_draft4.h
=> Centralize how we compute reference label hashes

src/evaluator/evaluator.cc, src/evaluator/include/sourcemeta/jsontoolkit/evaluator_template.h, src/jsonschema/compile_describe.cc, src/jsonschema/compile_json.cc, src/jsonschema/default_compiler_draft4.h, test/evaluator/evaluator_draft4_test.cc
=> Implement a "not" instruction that is not annotation-aware

src/jsonschema/walker.cc
This reverts commit 5ceffcc7c5149d65fbd07ad93e2f3ffa32a98023.
=> Don't use C++ ranges just yet (Emscripten support is limited)

DEPENDENCIES, src/json/include/sourcemeta/jsontoolkit/json.h, src/json/include/sourcemeta/jsontoolkit/json_error.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/jsonl/include/sourcemeta/jsontoolkit/jsonl.h, src/jsonl/include/sourcemeta/jsontoolkit/jsonl_iterator.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_error.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_anchor.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_bundle.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_error.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_reference.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/include/sourcemeta/jsontoolkit/uri_error.h, vendor/noa/cmake/noa/library.cmake
=> Use fully qualified includes for export headers

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_keyword_iterator_test.cc
=> Revise default walker keyword dependencies for compiler optimisations

src/jsonpointer/jsonpointer.cc, src/jsonschema/reference.cc, src/uri/include/sourcemeta/jsontoolkit/uri.h, src/uri/uri.cc, test/uri/uri_resolve_from_test.cc
=> Rename `resolve_from_if_absolute` to `try_resolve_from`

src/uri/uri.cc, test/jsonpointer/jsonpointer_to_uri_test.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/uri/uri_resolve_from_test.cc
=> Support resolving fragments on relative paths

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, test/json/json_array_test.cc, test/json/json_boolean_test.cc, test/json/json_integer_test.cc, test/json/json_null_test.cc, test/json/json_object_test.cc, test/json/json_real_test.cc, test/json/json_string_test.cc
=> Implement a fast hashing mechanism for JSON values

src/json/json_value.cc
=> Optimise uniqueness checks by hashing values

src/json/include/sourcemeta/jsontoolkit/json_object.h
=> Implement a fast constant hash function for object keys

src/json/CMakeLists.txt, src/json/include/sourcemeta/jsontoolkit/json.h, src/json/include/sourcemeta/jsontoolkit/json_hash.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, test/json/json_string_test.cc, test/json/json_value_test.cc
=> Expose general-purpose JSON hasher helpers

src/jsonpointer/jsonpointer.cc
=> Short-circuit Pointer traversal on empty Pointers

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h
=> Expose a Pointer method to reserve capacity

benchmark/CMakeLists.txt, benchmark/regex.cc
=> Benchmark common regular expressions

benchmark/regex.cc
=> Add a regex stress test to the benchmark

benchmark/regex.cc, src/regex/include/sourcemeta/jsontoolkit/regex.h, src/regex/regex.cc, test/regex/regex_matches_test.cc
=> Optimise regexes for non-empty strings

benchmark/regex.cc, test/regex/regex_matches_test.cc
=> Add more regex benchmarks and tests

src/regex/regex.cc
=> Improve regex prefix handling

src/regex/include/sourcemeta/jsontoolkit/regex.h, src/regex/regex.cc
=> Optimise range-based regexes

benchmark/regex.cc, src/regex/regex.cc
=> Improve optimisations for regexes for non-empty strings

benchmark/regex.cc, src/regex/regex.cc
=> Optimise more common regex cases

test/regex/regex_matches_test.cc, test/regex/regex_to_regex_test.cc
=> Add more regex test cases

src/regex/regex.cc
=> Consider `@` as a valid regex prefix character

benchmark/json.cc
=> Add a JSON parsing benchmark case

benchmark/json.cc
=> Benchmark object fast hashing and equality

src/json/include/sourcemeta/jsontoolkit/json.h, src/json/json.cc, src/json/parser.h, test/json/CMakeLists.txt, test/json/json_parse_callback_test.cc
=> Take an optional callback to obtain parse metadata

src/jsonpointer/CMakeLists.txt, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_position.h, src/jsonpointer/position.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_position_test.cc
=> Implement a helper class for mapping pointers to lines/columns

src/json/include/sourcemeta/jsontoolkit/json_object.h
=> Do not support mutable iterators in `Object`

benchmark/CMakeLists.txt, benchmark/jsonpointer.cc
=> Benchmark object pointer traversal

src/json/CMakeLists.txt, src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/json_value.cc, test/json/CMakeLists.txt, test/json/json_flat_map_test.cc
=> Implement a flat map container for JSON objects

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, src/jsonpointer/jsonpointer.cc, test/json/json_object_test.cc, test/jsonpointer/jsonpointer_token_test.cc
=> Pre-calculate property hashes in JSON Pointer

src/json/include/sourcemeta/jsontoolkit/json_hash.h
=> Cap key hash at 8 bits

src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_hash.h, test/json/CMakeLists.txt, test/json/json_flat_map_test.cc, test/json/json_hash_test.cc
=> Support perfect hashing for small JSON strings

src/json/include/sourcemeta/jsontoolkit/json_hash.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, test/json/json_hash_test.cc
=> Try to use 128-bit unsigned integers for string perfect hashes

src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/json_value.cc, test/json/json_flat_map_test.cc
=> Make `FlatMap` harder to use in non-performant manners

src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/jsonschema/jsonschema.cc, src/jsonschema/walker.cc, test/json/json_flat_map_test.cc, test/json/json_object_test.cc, test/jsonschema/referencingsuite.cc
=> Keep hash on the entry vector on `FlatMap`

src/jsonpointer/jsonpointer.cc
=> Improve readability when using `try_at` in JSON Pointer

src/json/CMakeLists.txt, src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc, test/json/CMakeLists.txt, test/json/json_flat_map_test.cc, test/json/json_object_test.cc
This reverts commit 40a4cee1befc24866a2ca1486dfb488a769e9b76.
=> Revert "Merge `FlatMap` into `JSONObject` (#1376)"

src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/json_value.cc
=> Implement a localized `defines()` method in `JSONObject`

src/jsonpointer/jsonpointer.cc
=> Avoid explicit iterators when possible on JSON Pointer

src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_object.h, src/json/json_value.cc, test/json/json_object_test.cc
=> Expose `.size()` in `JSONObject`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_flat_file_resolver_test.cc, test/jsonschema/schemas/2020-12-anonymous.json, test/jsonschema/schemas/2020-12-embedded.json, test/jsonschema/schemas/2020-12-id-duplicate.json, test/jsonschema/schemas/2020-12-id.json, test/jsonschema/schemas/2020-12-meta-1-schema.json, test/jsonschema/schemas/2020-12-meta-1.json, test/jsonschema/schemas/only-id.json
=> Implement a flat file schema resolver

src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/include/sourcemeta/jsontoolkit/json_hash.h, src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_token.h, test/json/json_hash_test.cc, test/json/json_string_test.cc
=> Simplify 128-bit string hashes to eventually cover a bigger range

src/json/include/sourcemeta/jsontoolkit/json_hash.h, test/json/json_hash_test.cc
=> Extend JSON property perfect hash to 256 bits

DEPENDENCIES, vendor/noa/cmake/noa/defaults.cmake, vendor/noa/cmake/noa/library.cmake
=> Upgrade Noa to enable fat LTO on LLVM and GCC

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_pointer.h, test/jsonpointer/jsonpointer_starts_with_initial_test.cc
=> Fix out of bounds crash on `starts_with_initial`

src/jsonschema/reference.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Detect dynamic references to a single possible dynamic anchor as static

benchmark/jsonpointer.cc
=> Benchmark pushing Pointers to weak Pointers

src/jsonschema/frame.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Mark subschemas in `.frame()`

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Extend `SchemaWalkerStrategy` to offer more precise types

src/jsonschema/CMakeLists.txt, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_unevaluated.h, src/jsonschema/unevaluated.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_test_utils.h, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc, test/jsonschema/jsonschema_unevaluated_2020_12_test.cc
=> Implement a helper for analysing `unevaluated(Properties|Items)`

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc
=> Mark `dependentSchemas` as an in-place applicator

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_walker.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Mark in-place applicators with special rules as `ApplicatorValueOther`

src/jsonschema/unevaluated.cc, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc
=> Ensure all `unevaluated` static dependencies are resolvable from the root

test/jsonschema/jsonschema_unevaluated_2019_09_test.cc
=> Add one more `anyOf` 2019-09 `unevaluated` dependency test

src/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h
=> Remove "wont-fix" TODO in JSON Pointer

src/json/include/sourcemeta/jsontoolkit/json_flat_map.h, src/json/json_value.cc, test/json/json_null_test.cc
=> Cleanup various JSON-related TODOs

src/jsonschema/frame.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend frame entries to record base dialects

src/jsonschema/bundle.cc, src/jsonschema/frame.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc
=> Detect unresolved fragments when bundling

src/uri/uri.cc, test/jsonpointer/jsonpointer_to_uri_test.cc, test/uri/uri_parse_test.cc, test/uri/uri_relative_to_test.cc, test/uri/uri_resolve_from_test.cc
=> Fix resolving relative URI paths with leading slashes

src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc, test/jsonschema/schemas/2020-12-id-casing.json
=> Make `FlatFileSchemaResolver` case-insensitive

src/jsonschema/bundle.cc, test/jsonschema/jsonschema_bundle_2019_09_test.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Ensure HyperSchema meta-schemas can be bundled

src/json/include/sourcemeta/jsontoolkit/json_hash.h
=> Support Clang on Ubuntu 22.04

CMakeLists.txt, test/yaml/CMakeLists.txt, test/yaml/yaml_parse_test.cc
=> Add initial unsuccessful YAML parsing tests

cmake/Findyaml.cmake, src/yaml/yaml.cc, test/yaml/yaml_parse_test.cc
=> Test parsing a scalar YAML document

src/yaml/yaml.cc, test/yaml/yaml_parse_test.cc
=> Finish a simple YAML integration

src/yaml/include/sourcemeta/jsontoolkit/yaml.h, src/yaml/yaml.cc, test/yaml/CMakeLists.txt, test/yaml/stubs/test_1.yaml, test/yaml/yaml_parse_test.cc
=> Add a `from_yaml` overload to read from an `std::filesystem::path`

src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_resolver.h, src/jsonschema/resolver.cc, test/jsonschema/jsonschema_flat_file_resolver_test.cc
=> Overload `FlatFileSchemaResolver::add` to manually take file contents

test/jsonschema/jsonschema_bundle_2019_09_test.cc
=> Add a smoke test for bundling HyperSchema 2019-09

src/jsonschema/default_walker.cc, test/jsonschema/jsonschema_bundle_draft4_test.cc, test/jsonschema/jsonschema_bundle_draft6_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Tweak `default_walker` to propertly recognise HyperSchema in Draft 4/6/7

src/jsonschema/default_walker.cc, src/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_keywords.h, src/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc
=> Introduce a new `Comment` keyword type

vendorpull.mask
=> Don't ship Noa when vendoring

DEPENDENCIES, src/json/include/sourcemeta/jsontoolkit/json_object.h, test/json/json_object_test.cc, vendor/noa/src/flat_map/include/sourcemeta/noa/flat_map.h
=> Support accessing object entries using positional indices

DEPENDENCIES, vendor/noa/src/flat_map/include/sourcemeta/noa/flat_map.h
=> Upgrade Noa to speed up `FlatMap` comparisons

src/json/include/sourcemeta/jsontoolkit/json_value.h, src/json/json_value.cc
=> Don't allow mutable references to JSON strings

vendor/noa/src/flat_map/include/sourcemeta/noa/flat_map.h
=> Make `FlatMap` accesors `noexcept`

benchmark/json.cc
=> Benchmark JSON string equality

benchmark/json.cc
=> Benchmark JSON object key containment misses

.github/workflows/ci.yml
=> Benchmark GCC on macOS

.github/workflows/website-deploy.yml
=> Fix GitHub Pages deployments

src/core/jsonpointer/CMakeLists.txt, src/core/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer.h, src/core/jsonpointer/include/sourcemeta/jsontoolkit/jsonpointer_proxy.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_proxy_test.cc
=> Implement a `PointerProxy` class

src/core/jsonschema/CMakeLists.txt, src/core/jsonschema/include/sourcemeta/jsontoolkit/jsonschema.h, src/core/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform.h, src/core/jsonschema/transform_rule.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_transform_rule_test.cc, test/jsonschema/jsonschema_transform_rules.h
=> Implement `TransformRule` in the JSON Schema module

src/core/jsonschema/CMakeLists.txt, src/core/jsonschema/include/sourcemeta/jsontoolkit/jsonschema_transform.h, src/core/jsonschema/transform_rule.cc, src/core/jsonschema/transformer.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_transform_rules.h, test/jsonschema/jsonschema_transformer_test.cc
=> Implement a `SchemaTransformer` class for JSON Schema

CMakeLists.txt
=> Offer GoogleTest and GoogleBenchmark to downstream components

CMakeLists.txt, doxygen/Doxyfile.in
=> Read Doxygen site name from CMake variables

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_position.h, src/core/jsonpointer/position.cc, src/core/yaml/include/sourcemeta/core/yaml.h, src/core/yaml/yaml.cc, test/jsonpointer/jsonpointer_position_test.cc, test/yaml/yaml_parse_test.cc
=> Revise Pointer and YAML public interfaces

src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc, test/uri/CMakeLists.txt, test/uri/uri_rebase_test.cc
=> Implement a new `URI::rebase` method

src/core/jsonschema/frame.cc, src/core/uri/uri.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/uri/uri_canonicalize_test.cc
=> Make sure identifiers are canonicalised during framing

test/jsonschema/jsonschema_relativize_test.cc
=> Test `reference_visitor_relativize` with camel case paths

src/core/jsonpointer/CMakeLists.txt, src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/jsonpointer.cc, src/core/jsonpointer/stringify.h, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_template_test.cc
=> Implement the idea of JSON Pointer templates

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/stringify.h, src/core/regex/include/sourcemeta/core/regex.h, test/jsonpointer/jsonpointer_template_test.cc
=> Support regular expression wildcards in `PointerTemplate`

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_pointer.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, test/jsonpointer/jsonpointer_pointer_test.cc, test/jsonpointer/jsonpointer_template_test.cc, test/jsonpointer/jsonpointer_weakpointer_test.cc
=> Revise `pop_back` on `Pointer` and `PointerTemplate`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/official_walker.cc, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_default_walker_2019_09_test.cc, test/jsonschema/jsonschema_default_walker_2020_12_test.cc, test/jsonschema/jsonschema_default_walker_draft0_test.cc, test/jsonschema/jsonschema_default_walker_draft1_test.cc, test/jsonschema/jsonschema_default_walker_draft2_test.cc, test/jsonschema/jsonschema_default_walker_draft3_test.cc, test/jsonschema/jsonschema_default_walker_draft4_test.cc, test/jsonschema/jsonschema_default_walker_draft6_test.cc, test/jsonschema/jsonschema_default_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Revise `SchemaKeywordType`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Report `relative_instance_location` on `SchemaFrame` location entries

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, test/jsonschema/jsonschema_test_utils.h
=> Rename `SchemaFrame` `relative_instance_location` to `instance_location`

test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Rename "default_walker" tests to "official_walker"

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Support multiple unresolved instance locations in `SchemaFrame`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Collect schema frame destinations as location references

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Collect all possible unresolved instance locations during framing

src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h
=> Add a performance-related TODO on `SchemaFrame`

benchmark/CMakeLists.txt, benchmark/jsonschema.cc, benchmark/schemas/2019_09_omc_json_v2.json, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h
=> Benchmark schema framing and bundling

src/core/json/include/sourcemeta/core/json_object.h
=> Make project build on older Clang

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Extend `SchemaIteratorEntry` with relative unresolved instance locations

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Expose location parents during framing

.github/workflows/ci.yml
=> Don't post benchmark comments from forks

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_test.cc
=> Ensure no instance locations in `References` framing mode

benchmark/jsonschema.cc, src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_unevaluated_2019_09_test.cc, test/jsonschema/jsonschema_unevaluated_2020_12_test.cc
=> Rename `Full` framing mode to `Instances`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_frame_test.cc
=> Add a new `Locations` mode for framing

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h
=> Rename `LocationsEntry` to `Location`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Remove `destination_of` from framing

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_test_utils.h
=> Add an `.instance_locations()` method to `SchemaFrame`

src/core/jsonschema/frame.cc
=> Inline `internal_analyse` in `SchemaFrame::analyse`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc
=> Move unresolved instance locations to their own frame map

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc
=> Get subschema parents for framed pointers

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h
=> Cleanup framing internal instance locations logic

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h
=> Implement a `SchemaFrame::references_to` method

benchmark/jsonschema.cc
=> Benchmark framing in `Locations` mode

test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Remove wrong TODO comment

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/stringify.h, test/jsonpointer/jsonpointer_template_test.cc
=> Implement a `Conditional` token for `PointerTemplate`

src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/official_walker.cc, src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Implement negation-oriented schema keyword types

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h, src/core/jsonpointer/stringify.h, src/core/jsonschema/walker.cc, test/jsonpointer/jsonpointer_template_test.cc
=> Rename `PointerTemplate` `Conditional` token to `Condition`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_test.cc
=> Implement a method to convert a `SchemaFrame` into JSON

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_test.cc
=> Support printing `SchemaFrame` to standard output streams

src/core/jsonpointer/include/sourcemeta/core/jsonpointer_template.h
=> Remove `PointerTemplate` wildcard assertions

test/uri/uri_relative_to_test.cc
=> Test `URI::relative_to` with absolute URIs and trailing slashes

src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/uri/uri_resolve_from_test.cc
=> Fix relative `$ref` on relative path `$id`

src/core/jsonschema/bundle.cc, src/core/jsonschema/frame.cc, src/core/jsonschema/jsonschema.cc
=> Revise various error messages

src/core/json/include/sourcemeta/core/json_object.h, src/core/json/include/sourcemeta/core/json_value.h, src/core/json/json_value.cc, src/extension/alterschema/desugar/const_as_enum.h, src/extension/alterschema/desugar/exclusive_maximum_integer_to_maximum.h, src/extension/alterschema/desugar/exclusive_minimum_integer_to_minimum.h, src/extension/alterschema/desugar/type_boolean_as_enum.h, src/extension/alterschema/desugar/type_null_as_enum.h, src/extension/alterschema/syntax_sugar/enum_to_const.h, test/json/json_object_test.cc
=> Implement a method to rename a JSON object property in-place

src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Add properties to `dependentSchemas`/`dependencies` instance locations

src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Add indexes to pointer templates from `anyOf` and `oneOf`

src/core/jsonschema/include/sourcemeta/core/jsonschema.h, src/core/jsonschema/jsonschema.cc, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_wrap_test.cc
=> Implement a utility function to wrap schemas

src/core/jsonschema/include/sourcemeta/core/jsonschema.h, src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_wrap_test.cc
=> Introduce a more general purpose subschema wrapping function

src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_wrap_test.cc
=> Support wrapping a schema given an empty pointer

src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h
=> Let the bundler construct transform rules with arguments

src/core/jsonschema/walker.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_transformer_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Framing must ignore `$schema` outside schema resources

DEPENDENCIES, vendor/jsonschema-draft4/links.json
=> Update JSON Schema Draft 4 schemas

src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, src/core/jsonpointer/jsonpointer.cc, test/jsonpointer/jsonpointer_weakpointer_test.cc
=> Implement a `to_weak_pointer` utility

src/core/jsonschema/include/sourcemeta/core/jsonschema_resolver.h, src/core/jsonschema/resolver.cc, test/jsonschema/jsonschema_map_resolver_test.cc
=> Extend `SchemaMapResolver::add` to return a boolean value

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_resolver.h, src/core/jsonschema/resolver.cc, test/jsonschema/jsonschema_map_resolver_test.cc
=> Extend `SchemaMapResolver::add` with an optional callback

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Support framing composite schema wrappers (i.e. OpenAPI)

src/core/jsonschema/bundle.cc
=> Note limitations of internal `bundle` frame for future reference

src/core/jsonschema/include/sourcemeta/core/jsonschema_error.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h, src/core/jsonschema/transformer.cc, test/alterschema/alterschema_test_utils.h, test/jsonschema/jsonschema_transform_rules.h, test/jsonschema/jsonschema_transformer_test.cc
=> Support defining unfixable schema transformation rules

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_2019_09_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_draft0_test.cc, test/jsonschema/jsonschema_frame_draft1_test.cc, test/jsonschema/jsonschema_frame_draft2_test.cc, test/jsonschema/jsonschema_frame_draft3_test.cc, test/jsonschema/jsonschema_frame_draft4_test.cc, test/jsonschema/jsonschema_frame_draft6_test.cc, test/jsonschema/jsonschema_frame_draft7_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_test_utils.h
=> Keep the original reference before resolution when framing

test/jsonschema/jsonschema_transform_rules.h, test/jsonschema/jsonschema_transformer_test.cc
=> Test transformers that remove identifiers

src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc, test/uri/uri_test.cc
=> Support constructing `std::map`s of `URI`

CMakeLists.txt
See: https://github.com/sourcemeta/core/pull/1645
=> Don't lint headers using ClangTidy

src/core/json/include/sourcemeta/core/json.h, src/core/jsonl/include/sourcemeta/core/jsonl.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, src/core/jsonschema/include/sourcemeta/core/jsonschema.h, src/core/uri/include/sourcemeta/core/uri.h, src/core/yaml/include/sourcemeta/core/yaml.h
Ref: https://github.com/sourcemeta/core/pull/1650#discussion_r2104799191
=> style(clang-tidy): Use use nolint on public headers

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_error.h, src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_bundle_test.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc, test/jsonschema/jsonschema_frame_test.cc, test/jsonschema/jsonschema_identify_test.cc, test/jsonschema/jsonschema_relativize_test.cc, test/jsonschema/jsonschema_vocabulary_test.cc, test/jsonschema/jsonschema_wrap_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1704
=> Throw more specific errors on unknown dialects / base dialects

src/core/jsonschema/frame.cc, src/core/jsonschema/jsonschema.cc, src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc, test/uri/uri_canonicalize_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1708
=> Implement a `URI::canonicalize()` helper static method

src/core/uri/include/sourcemeta/core/uri.h, src/core/uri/uri.cc, test/uri/uri_path_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1716
=> Implement a `URI::append_path` method

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, test/jsonschema/jsonschema_frame_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1721
=> Implement a `SchemaFrame::standalone` method

.github/workflows/ci.yml, test/json/jsontestsuite.cc
See: https://github.com/sourcemeta/blaze/issues/448
=> Run CI on MSYS2

cmake/common/targets/clang-tidy.config
=> style(clang-tidy): disable bugprone-empty-catch check

.github/workflows/ci.yml, cmake/common/targets/clang-format.cmake
=> Make formatting work in MSYS2

cmake/common/targets/clang-format.cmake
=> Show logs when failing to download `ClangFormat`

src/core/json/CMakeLists.txt, src/core/json/include/sourcemeta/core/json.h, src/core/json/include/sourcemeta/core/json_auto.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer_pointer.h, test/json/CMakeLists.txt, test/json/json_to_json_test.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_to_json_test.cc
=> Support a set of templates for converting classes to JSON

src/core/json/include/sourcemeta/core/json_auto.h, test/json/json_to_json_test.cc
=> Fix converting vector of pairs to JSON using `json_auto`

src/core/jsonschema/include/sourcemeta/core/jsonschema_types.h, src/core/jsonschema/official_walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc, test/jsonschema/jsonschema_walker_test.cc
=> Expose keyword instance types in the official walker

src/core/json/include/sourcemeta/core/json_auto.h
=> Prefix all concepts in `json_auto.h` with `json_auto_`

src/core/json/include/sourcemeta/core/json_auto.h
=> Expose re-usable tuple concepts in `json_auto.h`

src/core/json/include/sourcemeta/core/json_auto.h
=> Revise `json_auto_tuple_mono` to match the entire tuple

src/core/json/include/sourcemeta/core/json_auto.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, test/json/CMakeLists.txt, test/json/json_auto_test.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_json_auto_test.cc
=> Implement `from_json` template support in `json_auto.h`

src/core/uri/uri.cc, test/uri/uri_path_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1794
=> Allow setting a relative path in a relative URI

src/core/jsonschema/bundle.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h, src/core/jsonschema/transformer.cc, test/jsonschema/jsonschema_bundle_2020_12_test.cc, test/jsonschema/jsonschema_bundle_draft7_test.cc, test/jsonschema/jsonschema_bundle_test.cc
=> Take a default identifier on every `SchemaFrame` application

src/core/jsonschema/official_resolver.in.cc, test/jsonschema/jsonschema_official_resolver_test.cc
=> Resolve modern meta-schemas also with an empty fragment

src/core/json/parser.h, src/core/jsonpointer/parser.h, src/core/uri/escaping.cc, src/core/uri/uri.cc
=> fix cppcoreguidelines-init-variables checks

src/extension/alterschema/CMakeLists.txt, src/extension/alterschema/alterschema.cc, src/extension/alterschema/linter/unnecessary_allof_wrapper_properties.h, test/alterschema/alterschema_lint_2019_09_test.cc, test/alterschema/alterschema_lint_2020_12_test.cc, test/alterschema/alterschema_lint_draft4_test.cc, test/alterschema/alterschema_lint_draft6_test.cc, test/alterschema/alterschema_lint_draft7_test.cc
=> Implement a linting rule to merge up `properties` within `allOf`

src/core/json/include/sourcemeta/core/json_object.h
=> Make the `FlatMap` interface obsolete to consumers

src/core/jsonschema/bundle.cc
=> Avoid many unnecessary copies and computation in `bundle()`

src/core/jsonschema/bundle.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema.h, test/jsonschema/jsonschema_bundle_test.cc
=> Implement a trace callback for `.bundle()`

src/core/json/include/sourcemeta/core/json_object.h
=> Remove unintended invalid `noexcept`

src/core/jsonschema/CMakeLists.txt, src/core/jsonschema/bundle.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema.h, src/core/jsonschema/include/sourcemeta/core/jsonschema_bundle.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_bundle_test.cc, test/jsonschema/jsonschema_dependencies_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1879
=> Introduce a brand-new `dependencies` function

src/core/gzip/gzip.cc, src/core/gzip/include/sourcemeta/core/gzip.h, test/gzip/gzip_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1886
=> Refactor GZIP module to offer a full stream interface

CMakeLists.txt
=> Allow building contrib third party libraries without other modules

src/extension/alterschema/linter/non_applicable_type_specific_keywords.h, test/alterschema/alterschema_lint_2019_09_test.cc, test/alterschema/alterschema_lint_2020_12_test.cc, test/alterschema/alterschema_lint_draft1_test.cc, test/alterschema/alterschema_lint_draft2_test.cc, test/alterschema/alterschema_lint_draft3_test.cc, test/alterschema/alterschema_lint_draft4_test.cc, test/alterschema/alterschema_lint_draft6_test.cc, test/alterschema/alterschema_lint_draft7_test.cc
=> Remove non applicable type-specific keywords in terms of `const` and `enum`

src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_format_test.cc
=> Format custom keywords that "extend" existing keywords next to them

src/core/json/include/sourcemeta/core/json_array.h, src/core/jsonpointer/include/sourcemeta/core/jsonpointer.h, src/core/jsonpointer/jsonpointer.cc, test/jsonpointer/CMakeLists.txt, test/jsonpointer/jsonpointer_remove_test.cc
=> JSONPointer: add remove method

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1910
=> Convert `SchemaFrame` to JSON supporting O(1) lookups into location URIs

src/core/jsonschema/include/sourcemeta/core/jsonschema_error.h, src/core/jsonschema/jsonschema.cc, test/jsonschema/jsonschema_base_dialect_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1912
=> Report relative meta-schema resolution errors with a custom error

src/core/jsonschema/include/sourcemeta/core/jsonschema.h, src/core/jsonschema/jsonschema.cc, src/extension/alterschema/linter/non_applicable_type_specific_keywords.h, test/jsonschema/CMakeLists.txt, test/jsonschema/jsonschema_parse_type_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1919
=> Implement a `parse_schema_type` helper function

src/extension/alterschema/linter/enum_with_type.h, test/alterschema/alterschema_lint_2019_09_test.cc, test/alterschema/alterschema_lint_2020_12_test.cc, test/alterschema/alterschema_lint_draft1_test.cc, test/alterschema/alterschema_lint_draft2_test.cc, test/alterschema/alterschema_lint_draft3_test.cc, test/alterschema/alterschema_lint_draft4_test.cc, test/alterschema/alterschema_lint_draft6_test.cc, test/alterschema/alterschema_lint_draft7_test.cc
Fixes: https://github.com/sourcemeta/core/issues/1923
=> Revise the `enum_with_type` rule to match `type` in its array form

src/extension/alterschema/linter/unnecessary_allof_wrapper_draft.h, src/extension/alterschema/linter/unnecessary_allof_wrapper_modern.h, src/extension/alterschema/linter/unnecessary_allof_wrapper_properties.h
See: https://github.com/sourcemeta/jsonschema/issues/424
=> Clarify the reasons for discouraging unnecessary `allOf` wrappers

src/core/json/include/sourcemeta/core/json_auto.h, test/json/json_auto_test.cc
=> Extend `json_auto.h` to support `std::filesystem::file_time_type`

src/core/jsonschema/frame.cc, src/core/jsonschema/include/sourcemeta/core/jsonschema_frame.h, src/extension/alterschema/strict/required_properties_in_properties.h, test/alterschema/alterschema_lint_2020_12_test.cc
=> Consider `properties` on in-place applicators in `required_properties_in_properties`

src/core/jsonschema/include/sourcemeta/core/jsonschema_transform.h, test/jsonschema/jsonschema_transform_rules.h, test/jsonschema/jsonschema_transformer_test.cc
=> Add descriptions back to `SchemaTransformRule`

src/extension/editorschema/editorschema.cc, test/editorschema/editorschema_test.cc
=> Transform dynamic references to static locations in `for_editor`

src/core/jsonschema/official_walker.cc, test/jsonschema/jsonschema_official_walker_2019_09_test.cc, test/jsonschema/jsonschema_official_walker_2020_12_test.cc, test/jsonschema/jsonschema_official_walker_draft0_test.cc, test/jsonschema/jsonschema_official_walker_draft1_test.cc, test/jsonschema/jsonschema_official_walker_draft2_test.cc, test/jsonschema/jsonschema_official_walker_draft3_test.cc, test/jsonschema/jsonschema_official_walker_draft4_test.cc, test/jsonschema/jsonschema_official_walker_draft6_test.cc, test/jsonschema/jsonschema_official_walker_draft7_test.cc
=> Improve HyperSchema handling across dialects in `schema_official_walker`

src/core/jsonschema/include/sourcemeta/core/jsonschema_error.h, src/core/jsonschema/transformer.cc, test/jsonschema/jsonschema_transformer_test.cc
See: https://github.com/sourcemeta/jsonschema/issues/463
=> Improve exception when a transform rule is ran twice

src/core/jsonschema/frame.cc, test/jsonschema/jsonschema_frame_2020_12_test.cc
=> Fix framing bug on a schema with a relative `$id` and a default id

src/core/json/include/sourcemeta/core/json.h, src/core/json/json.cc, src/core/json/stringify.h, test/json/json_prettify_test.cc
=> Support custom number of indent spaces in `prettify`

src/core/json/include/sourcemeta/core/json_auto.h, test/json/json_auto_test.cc
=> Support converting maps of maps to JSON

src/extension/schemaconfig/parse.cc, test/schemaconfig/schemaconfig_from_json_test.cc, test/schemaconfig/schemaconfig_read_json_test.cc, test/schemaconfig/stub-valid-no-path.json
=> Make `path` optional in `SchemaConfig`
